#
msgid ""
msgstr ""
"Project-Id-Version: notmusicbot\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-11 16:38-0800\n"
"PO-Revision-Date: 2024-11-12 00:39\n"
"Last-Translator: \n"
"Language-Team: Japanese\n"
"Language: ja_JP\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-File: /fae/i18n/musicbot_logs.pot\n"
"X-Crowdin-File-ID: 26\n"
"X-Crowdin-Language: ja\n"
"X-Crowdin-Project: notmusicbot\n"
"X-Crowdin-Project-ID: 734017\n"
"X-Generated-By: pygettext.py 1.5-mb01\n"

#: musicbot/aliases.py:52
msgid "Aliases file not found, copying example_aliases.json"
msgstr "エイリアスファイルが見つかりません。example_aliases.json をコピー"

#: musicbot/aliases.py:56
msgid ""
"Error while loading aliases.\n"
"\n"
"Problem:\n"
"  Your aliases files (aliases.json & example_aliases.json) are missing.\n"
"\n"
"Solution:\n"
"  Replace the alias config file(s) or copy them from:\n"
"    https://github.com/Just-Some-Bots/MusicBot/"
msgstr ""

#: musicbot/aliases.py:80
#, python-format
msgid "Failed to load aliases file:  %s"
msgstr "エイリアスファイルの読み込みに失敗しました:  %s"

#: musicbot/aliases.py:88
#, python-format
msgid ""
"Failed to parse aliases file:  %s\n"
"Ensure the file contains valid JSON and restart the bot."
msgstr ""
"エイリアスファイルの解析に失敗しました:  %s\n"
"ファイルに有効な JSON が含まれていることを確認し、ボットを再起動します。"

#: musicbot/aliases.py:114
#, python-format
msgid ""
"Aliases skipped for non-existent command:  %(command)s  ->  %(aliases)s"
msgstr "エイリアスは存在しないコマンドでスキップされました:  %(command)s  ->  %(aliases)s"

#: musicbot/aliases.py:122
#, python-format
msgid ""
"Alias(es) skipped for invalid alias data:  %(command)s  ->  %(aliases)s"
msgstr "エイリアスが無効なエイリアスデータに対してスキップされました:  %(command)s  ->  %(aliases)s"

#: musicbot/aliases.py:135
#, python-format
msgid "Alias `%(alias)s` skipped as already exists on command:  %(command)s"
msgstr "エイリアス `%(alias)s` はコマンド  %(command)s で既に存在するようスキップされました。"

#: musicbot/autoplaylist.py:77
#, python-format
msgid "Error loading auto playlist file:  %s"
msgstr "自動プレイリストファイルの読み込みエラー:  %s"

#: musicbot/autoplaylist.py:181
#, python-format
msgid "Removing unplayable song from playlist, %(playlist)s: %(track)s"
msgstr "プレイリストから再生できない曲を削除しています。 %(playlist)s: %(track)s"

#: musicbot/autoplaylist.py:186
#, python-format
msgid "Removing song from playlist, %(playlist)s: %(track)s"
msgstr "プレイリストから曲を削除しています。 %(playlist)s: %(track)s"

#: musicbot/autoplaylist.py:132 musicbot/autoplaylist.py:211
msgid "Could not log information about the playlist URL removal."
msgstr "プレイリストURLの削除に関する情報を記録できませんでした。"

#: musicbot/autoplaylist.py:135 musicbot/autoplaylist.py:215
msgid "Updating playlist file..."
msgstr "プレイリストファイルを更新しています..."

#: musicbot/autoplaylist.py:158 musicbot/autoplaylist.py:231
#: musicbot/autoplaylist.py:268
#, python-format
msgid "Failed to save playlist file:  %s"
msgstr "プレイリストファイルの保存に失敗しました:  %s"

#: musicbot/autoplaylist.py:240
#, python-format
msgid "URL already in playlist %s, ignoring"
msgstr "プレイリスト %sのURLは既に無視されています"

#: musicbot/autoplaylist.py:247
#, python-format
msgid "Adding new URL to playlist, %(playlist)s: %(track)s"
msgstr "プレイリストに新しいURLを追加しています。 %(playlist)s: %(track)s"

#: musicbot/bot.py:167
#, python-format
msgid "Initializing MusicBot %s"
msgstr "MusicBot %s の初期化中"

#: musicbot/bot.py:250
#, python-format
msgid "Loop is closed, cannot create task for: %r"
msgstr "ループが閉じられています。次のタスクを作成できません: %r"

#: musicbot/bot.py:266
#, python-format
msgid "Unhandled exception for task:  %r"
msgstr "タスクの未処理例外:  %r"

#: musicbot/bot.py:270
#, python-format
msgid "Unhandled exception for task:  %(task)r  --  %(raw_error)s"
msgstr "タスクの未処理例外:  %(task)r --  %(raw_error)s"

#: musicbot/bot.py:315 musicbot/bot.py:337
msgid "Spotify did not provide us with a token. Disabling."
msgstr "Spotifyはトークンを提供していません。無効にしています。"

#: musicbot/bot.py:319
msgid "Authenticated with Spotify successfully using client ID and secret."
msgstr "クライアント ID とシークレットを使用して Spotify で正常に認証されました。"

#: musicbot/bot.py:323
#, python-format
msgid ""
"Could not start Spotify client. Is your client ID and secret correct? "
"Details: %s. Continuing anyway in 5 seconds..."
msgstr "Spotifyクライアントを起動できませんでした。クライアントIDと秘密情報は正しいですか？詳細： %s。とにかく5秒後に続行します..."

#: musicbot/bot.py:331
msgid ""
"The config did not have Spotify app credentials, attempting to use guest "
"mode."
msgstr "設定にはSpotifyアプリの資格情報がありませんでした。ゲストモードを使用しようとしています。"

#: musicbot/bot.py:341
msgid "Authenticated with Spotify successfully using guest mode."
msgstr "ゲストモードで Spotify で正常に認証されました。"

#: musicbot/bot.py:346
#, python-format
msgid "Could not start Spotify client using guest mode. Details: %s."
msgstr "ゲストモードでSpotifyクライアントを起動できませんでした。詳細: %s."

#: musicbot/bot.py:354
msgid ""
"Experimental Yt-dlp OAuth2 plugin is enabled. This might break at any point!"
msgstr "実験的な Yt-dlp OAuth2 プラグインが有効になっています。これはいつでも壊れる可能性があります！"

#: musicbot/bot.py:361
msgid "Initialized, now connecting to discord."
msgstr "初期化されました。今すぐDiscordに接続しています。"

#: musicbot/bot.py:372
msgid "Network ping test is disabled via config."
msgstr "ネットワーク接続テストは設定で無効になっています。"

#: musicbot/bot.py:376
msgid "Network ping test is closing down."
msgstr "ネットワーク接続テストは終了しています。"

#: musicbot/bot.py:387
msgid "Could not resolve ping target."
msgstr "ターゲットを解決できませんでした。"

#: musicbot/bot.py:417
msgid "Network ping test cancelled."
msgstr "ネットワーク接続テストがキャンセルされました。"

#: musicbot/bot.py:431
msgid "Network testing via HTTP does not have a session to borrow."
msgstr "HTTP経由のネットワークテストには、借りるセッションがありません。"

#: musicbot/bot.py:456
msgid "Could not locate `ping` executable in your environment."
msgstr "環境で `ping` 実行ファイルが見つかりませんでした。"

#: musicbot/bot.py:482
#, python-format
msgid ""
"MusicBot could not locate a `ping` command path.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""

#: musicbot/bot.py:492
#, python-format
msgid ""
"MusicBot was denied permission to execute the `ping` command.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""

#: musicbot/bot.py:502
#, python-format
msgid ""
"Your environment may not allow the `ping` system command.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""

#: musicbot/bot.py:517
msgid "MusicBot detected network is available again."
msgstr "MusicBot が検出されたネットワークは再び利用可能です。"

#: musicbot/bot.py:522
msgid "VoiceClient is not connected, waiting to resume MusicPlayer..."
msgstr "VoiceClientが接続されていません。MusicPlayerの再開を待機しています..."

#: musicbot/bot.py:526
#, python-format
msgid "Resuming playback of player:  (%(guild_id)s) %(player)r"
msgstr "プレーヤーの再生再開: (%(guild_id)s) %(player)r"

#: musicbot/bot.py:537
msgid "MusicBot detected a network outage."
msgstr "MusicBotはネットワーク停止を検出しました。"

#: musicbot/bot.py:541
#, python-format
msgid ""
"Pausing MusicPlayer due to network availability:  (%(guild_id)s) %(player)r"
msgstr "ネットワークの空き状況によりMusicPlayerを一時停止: (%(guild_id)s) %(player)r"

#: musicbot/bot.py:562
#, python-format
msgid ""
"Looking for owner in guild: %(guild)s (required voice: %(required)s) and "
"got:  %(owner)s"
msgstr "ギルドで所有者を探しています: %(guild)s (必須音声: %(required)s) と得点:  %(owner)s"

#: musicbot/bot.py:576
msgid "Checking for channels to auto-join or resume..."
msgstr "自動参加または再開するチャンネルを確認しています..."

#: musicbot/bot.py:588
#, python-format
msgid "Guild not available, cannot auto join:  %(id)s/%(name)s"
msgstr "ギルドが利用できません。自動参加できません:  %(id)s/%(name)s"

#: musicbot/bot.py:596
#, python-format
msgid "Found resumable voice channel:  %(channel)s  in guild:  %(guild)s"
msgstr "再開可能なボイスチャンネルが見つかりました：ギルド内の  %(channel)s  ：  %(guild)s"

#: musicbot/bot.py:609
#, python-format
msgid "Will try resuming voice session instead of Auto-Joining channel:  %s"
msgstr "自動接続チャンネルの代わりに音声セッションを再開してみます:  %s"

#: musicbot/bot.py:626
#, python-format
msgid "Found owner in voice channel:  %s"
msgstr "音声チャンネルの所有者が見つかりました:  %s"

#: musicbot/bot.py:631
#, python-format
msgid "Ignoring resumable channel, AutoSummon to owner in channel:  %s"
msgstr "再開可能なチャネルを無視して、チャンネル内の所有者へのAutoSummon :  %s"

#: musicbot/bot.py:636
#, python-format
msgid "Ignoring Auto-Join channel, AutoSummon to owner in channel:  %s"
msgstr "自動参加チャンネルを無視しました。チャンネルの所有者に自動召喚:  %s"

#: musicbot/bot.py:648
#, python-format
msgid "Already connected to channel:  %(channel)s  in guild:  %(guild)s"
msgstr "既にチャンネルに接続されています: ギルド内の  %(channel)s  :  %(guild)s"

#: musicbot/bot.py:657
#, python-format
msgid "Attempting to join channel:  %(channel)s  in guild:  %(guild)s"
msgstr "チャンネルへの参加を試みています: ギルドの  %(channel)s  :  %(guild)s"

#: musicbot/bot.py:664
msgid "Discarding MusicPlayer and making a new one..."
msgstr "MusicPlayerを破棄し、新しいMusicPlayerを作成しています..."

#: musicbot/bot.py:684
msgid "MusicBot will make a new MusicPlayer now..."
msgstr "MusicBotが新しいMusicPlayerを作成します..."

#: musicbot/bot.py:705
#, python-format
msgid "Not joining %(guild)s/%(channel)s, it isn't a supported voice channel."
msgstr "%(guild)s/%(channel)sに参加していません。サポートされているボイスチャンネルではありません。"

#: musicbot/bot.py:708
msgid "Finished joining configured channels."
msgstr "設定されたチャンネルへの参加が終了しました。"

#: musicbot/bot.py:720
msgid "Member is not voice-enabled and cannot use this command."
msgstr "メンバーは音声対応ではないため、このコマンドは使用できません。"

#: musicbot/bot.py:728
msgid "You cannot use this command when not in the voice channel."
msgstr "ボイスチャンネルでない場合、このコマンドは使用できません。"

#: musicbot/bot.py:742
msgid "Getting bot Application Info."
msgstr "Botアプリケーション情報を取得しています。"

#: musicbot/bot.py:767
#, python-format
msgid "MusicBot does not have permission to Connect in channel:  %s"
msgstr "MusicBot にチャンネルへの接続権限がありません:  %s"

#: musicbot/bot.py:771
#, python-format
msgid "MusicBot does not have permission to Connect in channel:  `%(name)s`"
msgstr "MusicBotにチャンネルで接続する権限がありません: `%(name)s`"

#: musicbot/bot.py:776
#, python-format
msgid "MusicBot does not have permission to Speak in channel:  %s"
msgstr "MusicBot にチャンネル内で話す権限がありません:  %s"

#: musicbot/bot.py:780
#, python-format
msgid "MusicBot does not have permission to Speak in channel:  `%(name)s`"
msgstr "MusicBotにチャンネルで話す権限がありません: `%(name)s`"

#: musicbot/bot.py:790
#, python-format
msgid "Reusing bots VoiceClient from guild:  %s"
msgstr "ギルドからボットVoiceClientを再利用:  %s"

#: musicbot/bot.py:795
#, python-format
msgid "Forcing disconnect on stale VoiceClient in guild:  %s"
msgstr "ギルド内の古いVoiceClientの切断を強制:  %s"

#: musicbot/bot.py:801
msgid "Disconnect failed or was cancelled?"
msgstr "切断に失敗したか、キャンセルされましたか？"

#: musicbot/bot.py:809
#, python-format
msgid "MusicBot is unable to connect to the channel right now:  %(channel)s"
msgstr "MusicBotは現在チャンネルに接続できません:  %(channel)s"

#: musicbot/bot.py:813
msgid ""
"MusicBot could not connect to the channel.\n"
"Try again later, or restart the bot if this continues."
msgstr ""
"MusicBot がチャンネルに接続できませんでした。\n"
"後でもう一度試すか、続行するとボットを再起動してください。"

#: musicbot/bot.py:824
msgid "MusicBot has a VoiceClient now..."
msgstr "MusicBotには現在VoiceClientがあります..."

#: musicbot/bot.py:829
#, python-format
msgid ""
"Retrying connection after a timeout error (%(attempt)s) while trying to "
"connect to:  %(channel)s"
msgstr "接続中にタイムアウトエラー (%(attempt)s) の後に接続を再試行しています:  %(channel)s"

#: musicbot/bot.py:834
msgid "MusicBot VoiceClient connection attempt was cancelled. No retry."
msgstr "MusicBot VoiceClient 接続がキャンセルされました。再試行しません。"

#: musicbot/bot.py:837
msgid ""
"MusicBot connection to voice was cancelled. This is odd. Maybe restart?"
msgstr "ボイスチャットへのMusicBot接続がキャンセルされました。これは奇妙です。再起動しますか？"

#: musicbot/bot.py:843 musicbot/bot.py:8543
#, python-format
msgid "MusicBot is requesting to speak in channel: %s"
msgstr "MusicBot がチャンネルでのスピーキングをリクエストしています: %s"

#: musicbot/bot.py:848 musicbot/bot.py:8549
msgid "MusicBot does not have permission to speak."
msgstr "MusicBot には話す権限がありません。"

#: musicbot/bot.py:852 musicbot/bot.py:8551
msgid "MusicBot could not request to speak."
msgstr "MusicBot は話すことができませんでした。"

#: musicbot/bot.py:865
#, python-format
msgid "Disconnecting a MusicPlayer in guild:  %s"
msgstr "ギルドでMusicPlayerを切断:  %s"

#: musicbot/bot.py:877
msgid "Disconnecting VoiceClient before we kill the MusicPlayer."
msgstr "MusicPlayerを停止する前にVoiceClientを切断します。"

#: musicbot/bot.py:885 musicbot/bot.py:904 musicbot/bot.py:916
#: musicbot/bot.py:939
msgid "The disconnect failed or was cancelled."
msgstr "切断に失敗またはキャンセルされました。"

#: musicbot/bot.py:895
msgid ""
"MusicBot has a VoiceProtocol that is not a VoiceClient. Disconnecting "
"anyway..."
msgstr "MusicBotにはVoiceClientではないVoiceProtocolがあります。とにかく接続を解除してください。"

#: musicbot/bot.py:908
#, python-format
msgid "Disconnecting a rogue VoiceClient in guild:  %s"
msgstr "ギルド内の不正なVoiceClientの接続を切断:  %s"

#: musicbot/bot.py:932
msgid "Disconnecting a non-guild VoiceClient..."
msgstr "ギルド以外のVoiceClientの接続を切断..."

#: musicbot/bot.py:942
#, python-format
msgid ""
"MusicBot.voice_clients list contains a non-VoiceClient object?\n"
"The object is actually of type:  %s"
msgstr ""
"MusicBot.voice_clients リストに、VoiceClient 以外のオブジェクトが含まれていますか？\n"
"オブジェクトは実際は型です。  %s"

#: musicbot/bot.py:952
#, python-format
msgid "We still have a MusicPlayer ref in guild (%(guild_id)s):  %(player)r"
msgstr "ギルド内にMusicPlayerのrefがあります (%(guild_id)s):  %(player)r"

#: musicbot/bot.py:965
#, python-format
msgid "Guild (%(guild)s) wants a player, optional:  %(player)r"
msgstr "Guild (%(guild)s) はプレイヤー、任意の  %(player)r を要求しています"

#: musicbot/bot.py:972
msgid ""
"[BUG] MusicPlayer is missing a VoiceClient somehow.  You should probably "
"restart the bot."
msgstr "[BUG] MusicPlayerにVoiceClientがありません。おそらく再起動してください。"

#: musicbot/bot.py:977
msgid "MusicPlayer has a VoiceClient that is not connected."
msgstr "MusicPlayer に接続されていない VoiceClient があります。"

#: musicbot/bot.py:978
#, python-format
msgid "MusicPlayer obj:  %r"
msgstr "MusicPlayer obj:  %r"

#: musicbot/bot.py:979
#, python-format
msgid "VoiceClient obj:  %r"
msgstr "VoiceClient obj:  %r"

#: musicbot/bot.py:999
#, python-format
msgid ""
"Getting a MusicPlayer for guild:  %(guild)s  In Channel:  %(channel)s  "
"Create: %(create)s  Deserialize:  %(serial)s"
msgstr ""
"ギルドでMusicPlayerを取得する:  %(guild)s  チャンネルで:  %(channel)s  作成: %(create)s  "
"デシリアライズ:  %(serial)s"

#: musicbot/bot.py:1015
#, python-format
msgid ""
"Created player via deserialization for guild %(guild_id)s with %(number)s "
"entries"
msgstr "ギルド %(guild_id)s の %(number)s エントリーでデシリアライゼーションを経由してプレイヤーを作成"

#: musicbot/bot.py:1024
msgid ""
"The bot is not in a voice channel.\n"
"Use the summon command to bring the bot to your voice channel."
msgstr ""
"ボットはボイスチャンネルに入っていません。\n"
"召喚コマンドを使ってボットをボイスチャンネルに連れてきてください。"

#: musicbot/bot.py:1036
msgid "Something is wrong, we didn't get the VoiceClient."
msgstr "問題が発生しました。VoiceClientを取得できませんでした。"

#: musicbot/bot.py:1069
msgid "Running on_player_play"
msgstr "実行中のplayer_play"

#: musicbot/bot.py:1144
#, python-format
msgid "Setting URL history guild %(guild_id)s == %(url)s"
msgstr "URL履歴を設定する ギルド %(guild_id)s == %(url)s"

#: musicbot/bot.py:1180 musicbot/bot.py:4858
#, python-format
msgid "No thumbnail set for entry with URL: %s"
msgstr "URLのエントリに設定されたサムネイルはありません: %s"

#: musicbot/bot.py:1192
msgid "no channel to put now playing message into"
msgstr "メッセージを再生するチャンネルがありません"

#: musicbot/bot.py:1204
msgid "ignored now-playing message as it was already posted."
msgstr "既に投稿されていたメッセージは無視されました。"

#: musicbot/bot.py:1228
msgid "Running on_player_resume"
msgstr "実行中のplayer_resume"

#: musicbot/bot.py:1241
msgid "Running on_player_pause"
msgstr "player_pause実行中"

#: musicbot/bot.py:1257
msgid "Running on_player_stop"
msgstr "実行中のplayer_stop"

#: musicbot/bot.py:1267
msgid "Running on_player_finished_playing"
msgstr "実行中の on_player_finished_playing"

#: musicbot/bot.py:1269 musicbot/bot.py:1315 musicbot/bot.py:1386
msgid "Event loop is closed, nothing else to do here."
msgstr "イベントループは閉じられています。ここで行うことは何もありません。"

#: musicbot/bot.py:1273 musicbot/bot.py:1319 musicbot/bot.py:1390
msgid "Logout under way, ignoring this event."
msgstr "このイベントを無視して進行中にログアウトします。"

#: musicbot/bot.py:1290
msgid "VoiceClient says it is not connected, nothing else we can do here."
msgstr "VoiceClient は、接続されていない、ここでできることは何もありません。"

#: musicbot/bot.py:1297
msgid "Player finished and queue is empty, leaving voice channel..."
msgstr "プレーヤーが終了し、キューが空です。ボイスチャンネルを残しています..."

#: musicbot/bot.py:1311
msgid "Looping over queue to expunge songs with missing author..."
msgstr "不足している曲を削除するためにキューをループさせています..."

#: musicbot/bot.py:1350
#, python-format
msgid ""
"Author `%(user)s` absent, skipped (deleted) entry from queue:  %(song)s"
msgstr "Author `%(user)s` 欠席、スキップされた(削除された)エントリ:  %(song)s"

#: musicbot/bot.py:1369
msgid "No playable songs in the Guild autoplaylist, disabling."
msgstr "ギルドの自動プレイリストに再生可能な曲がありません。"

#: musicbot/bot.py:1374
msgid "No content in current autoplaylist. Filling with new music..."
msgstr "現在の自動再生リストにはコンテンツがありません。新しい音楽で塗りつぶします..."

#: musicbot/bot.py:1382
msgid "Looping over player autoplaylist..."
msgstr "プレーヤーの自動再生リストの上にループしています..."

#: musicbot/bot.py:1423
#, python-format
msgid "Error while processing song \"%(url)s\":  %(raw_error)s"
msgstr "曲「%(url)s」の処理中にエラーが発生しました：  %(raw_error)s"

#: musicbot/bot.py:1434
#, python-format
msgid "Error extracting song \"%(url)s\": %(raw_error)s"
msgstr "曲 \"%(url)s\" の抽出中にエラーが発生しました： %(raw_error)s"

#: musicbot/bot.py:1449
msgid "MusicBot needs to stop the auto playlist extraction and bail."
msgstr "MusicBotは自動プレイリストの抽出と保釈を停止する必要があります。"

#: musicbot/bot.py:1454
msgid "MusicBot got an unhandled exception in player finished event."
msgstr "MusicBotはプレイヤーの終了イベントで処理されていない例外を受け取りました。"

#: musicbot/bot.py:1460
#, python-format
msgid "Expanding auto playlist with entries extracted from:  %s"
msgstr "%s から抽出されたエントリで自動プレイリストを展開します"

#: musicbot/bot.py:1484
#, python-format
msgid "Error adding song from autoplaylist: %s"
msgstr "自動再生リストから曲を追加中にエラーが発生しました: %s"

#: musicbot/bot.py:1487
msgid "Exception data for above error:"
msgstr "上記のエラーの例外データ:"

#: musicbot/bot.py:1493
msgid "No playable songs in the autoplaylist, disabling."
msgstr "自動プレイリストに再生可能な曲がありません。無効にします。"

#: musicbot/bot.py:1513
msgid "Running on_player_entry_added"
msgstr "実行中 on_player_entry_added"

#: musicbot/bot.py:1523
msgid "Automatically skipping auto-playlist entry for queued entry."
msgstr "キューに入れられたエントリの自動プレイリストのエントリを自動的にスキップします。"

#: musicbot/bot.py:1543
#, python-format
msgid "MusicPlayer exception for entry: %r"
msgstr "エントリの MusicPlayer 例外: %r"

#: musicbot/bot.py:1549
msgid "MusicPlayer exception."
msgstr "MusicPlayer例外です。"

#: musicbot/bot.py:1573
#, python-format
msgid "Auto playlist track could not be played:  %r"
msgstr "自動プレイリストトラックを再生できませんでした:  %r"

#: musicbot/bot.py:1612
msgid "Logout under way, ignoring status update event."
msgstr "状態更新イベントを無視して進行中のログアウトします。"

#: musicbot/bot.py:1713
#, python-format
msgid "Update bot status:  %(status)s -- %(activity)r"
msgstr "ボットのステータスを更新:  %(status)s -- %(activity)r"

#: musicbot/bot.py:1741
#, python-format
msgid "Serializing queue for %s"
msgstr "キューを %sにシリアライズ中"

#: musicbot/bot.py:1767
#, python-format
msgid "Deserializing queue for %s"
msgstr "%sのキューをデシリアライズしています"

#: musicbot/bot.py:1785
#, python-format
msgid "Writing current song for %s"
msgstr "%s のために現在の曲を書き込み中"

#: musicbot/bot.py:1810
#, python-format
msgid "Cannot send non-response object:  %r"
msgstr "応答しないオブジェクトを送信できません:  %r"

#: musicbot/bot.py:1815
msgid "[Dev Bug] Tried sending an invalid response object."
msgstr "無効なレスポンスオブジェクトを送信しようとしました。"

#: musicbot/bot.py:1843
#, python-format
msgid "sending embed to: %s"
msgstr "%s に埋め込みを送信中"

#: musicbot/bot.py:1846
#, python-format
msgid "sending text to: %s"
msgstr "%s にテキストを送信しています"

#: musicbot/bot.py:1851
#, python-format
msgid "Cannot send message to \"%s\", no permission"
msgstr "\"%s\"にメッセージを送信できません。権限がありません"

#: musicbot/bot.py:1858
#, python-format
msgid "Cannot send message to \"%s\", invalid or deleted channel"
msgstr "\"%s\"にメッセージを送信できません。無効または削除されたチャンネル"

#: musicbot/bot.py:1866
#, python-format
msgid "Message is over the message size limit (%s)"
msgstr "メッセージのサイズ制限を超えています（%s）"

#: musicbot/bot.py:1874
msgid "Could not send private message, sending in fallback channel instead."
msgstr "代わりにフォールバックチャンネルを送信してプライベートメッセージを送信できませんでした。"

#: musicbot/bot.py:1892
#, python-format
msgid "Rate limited send message, retrying in %s seconds."
msgstr "レート制限されたメッセージを送信し、 %s 秒後に再試行します。"

#: musicbot/bot.py:1898
#, python-format
msgid "Cancelled message retry for:  %s"
msgstr "キャンセルされたメッセージの再試行:  %s"

#: musicbot/bot.py:1903
msgid "Rate limited send message, but cannot retry!"
msgstr "制限されたメッセージの送信を評価するが、再試行することはできません！"

#: musicbot/bot.py:1909
msgid "Failed to send message in fallback channel."
msgstr "フォールバックチャンネルでメッセージを送信できませんでした。"

#: musicbot/bot.py:1914 musicbot/bot.py:1978 musicbot/bot.py:2048
msgid "Failed to send due to an HTTP error."
msgstr "HTTPエラーのため送信に失敗しました。"

#: musicbot/bot.py:1940
#, python-format
msgid "Cannot delete message \"%s\", no permission"
msgstr "メッセージ「%s」を削除できません。権限がありません"

#: musicbot/bot.py:1945
#, python-format
msgid "Cannot delete message \"%s\", message not found"
msgstr "メッセージ \"%s\" を削除できません。メッセージが見つかりません。"

#: musicbot/bot.py:1963
#, python-format
msgid "Rate limited message delete, retrying in %s seconds."
msgstr "Rate limited message delete, retrying in %s seconds."

#: musicbot/bot.py:1968
msgid "Rate limited message delete, but cannot retry!"
msgstr "制限されたメッセージの削除を評価しますが、再試行できません！"

#: musicbot/bot.py:1971
msgid "Failed to delete message"
msgstr "メッセージの削除に失敗しました"

#: musicbot/bot.py:1973
#, python-format
msgid "Got HTTPException trying to delete message: %s"
msgstr "HTTPExceptionがメッセージを削除しようとしています: %s"

#: musicbot/bot.py:2008
#, python-format
msgid "Cannot edit message \"%s\", message not found"
msgstr "メッセージ \"%s\" を編集できません。メッセージが見つかりません。"

#: musicbot/bot.py:2012
msgid "Sending message instead"
msgstr "代わりにメッセージを送信中"

#: musicbot/bot.py:2029
#, python-format
msgid "Rate limited edit message, retrying in %s seconds."
msgstr "制限された編集メッセージを評価し、 %s 秒後に再試行します。"

#: musicbot/bot.py:2035
#, python-format
msgid "Cancelled message edit for:  %s"
msgstr "%s へのメッセージ編集をキャンセルしました"

#: musicbot/bot.py:2041
msgid "Failed to edit message"
msgstr "メッセージの編集に失敗しました"

#: musicbot/bot.py:2043
#, python-format
msgid "Got HTTPException trying to edit message %s to: %s"
msgstr "HTTPExceptionがメッセージ %s を編集しようとしています: %s"

#: musicbot/bot.py:2065
#, python-format
msgid "Cancelled delete for message (ID: %(id)s):  %(content)s"
msgstr "メッセージの削除をキャンセルしました (ID: %(id)s):  %(content)s"

#: musicbot/bot.py:2127
#, python-format
msgid "Caught a signal from the OS: %s"
msgstr "OSからの信号をキャッチしました： %s"

#: musicbot/bot.py:2131
msgid "Disconnecting and closing down MusicBot..."
msgstr "MusicBotの接続を切断して閉じます..."

#: musicbot/bot.py:2134
msgid "Exception thrown while handling interrupt signal!"
msgstr "割込み信号の処理中に例外がスローされました！"

#: musicbot/bot.py:2149
msgid "MusicBot is now doing shutdown steps..."
msgstr "MusicBot がシャットダウンステップを行っています..."

#: musicbot/bot.py:2157
msgid ""
"Failed Discord API Login!\n"
"\n"
"Problem:\n"
"  MusicBot could not log into Discord API.\n"
"  Your Token may be incorrect or there may be an API outage.\n"
"\n"
"Solution:\n"
"  Make sure you have the correct Token set in your config.\n"
"  Check API status at the official site: discordstatus.com"
msgstr ""

#: musicbot/bot.py:2171
msgid "Waiting for download threads to finish up..."
msgstr "ダウンロードスレッドが終了するのを待っています..."

#: musicbot/bot.py:2197
#, python-format
msgid "Will wait for task:  %(name)s  (%(func)s)"
msgstr "Will wait for task:  %(name)s  (%(func)s)"

#: musicbot/bot.py:2204
#, python-format
msgid "Will try to cancel task:  %(name)s  (%(func)s)"
msgstr "タスクをキャンセルしようとします:  %(name)s  (%(func)s)"

#: musicbot/bot.py:2212
msgid "Awaiting pending tasks..."
msgstr "保留中のタスクを待機しています..."

#: musicbot/bot.py:2218
msgid "Closing HTTP Connector."
msgstr "HTTP コネクタを閉じています。"

#: musicbot/bot.py:2224
msgid "Closing aiohttp session."
msgstr "aiohttp セッションを閉じています。"

#: musicbot/bot.py:2236
msgid "Logout has been called."
msgstr "ログアウトを呼び出しました。"

#: musicbot/bot.py:2248
#, python-format
msgid ""
"Exception in %(event)s:\n"
"%(error)s"
msgstr ""
"%(event)sの例外 :\n"
"%(error)s"

#: musicbot/bot.py:2264
#, python-format
msgid "Exception in %s"
msgstr "%s の例外"

#: musicbot/bot.py:2271
msgid "MusicBot resumed a session with discord."
msgstr "MusicBotはdiscordとのセッションを再開しました。"

#: musicbot/bot.py:2288
msgid "Finish on_ready"
msgstr "完了(_L)"

#: musicbot/bot.py:2295
msgid "Logged in, now getting MusicBot ready..."
msgstr "ログイン中、MusicBot の準備中..."

#: musicbot/bot.py:2298
msgid "ClientUser is somehow none, we gotta bail..."
msgstr "クライアントユーザーは何らかの形ではありません。保釈する必要があります..."

#: musicbot/bot.py:2307
#, python-format
msgid "MusicBot:  %(id)s/%(name)s#%(desc)s"
msgstr "MusicBot:  %(id)s/%(name)s#%(desc)s"

#: musicbot/bot.py:2318
#, python-format
msgid "Owner:     %(id)s/%(name)s#%(desc)s\n"
msgstr "所有者:     %(id)s/%(name)s#%(desc)s\n"

#: musicbot/bot.py:2326 musicbot/bot.py:2353
msgid "Guild List:"
msgstr "ギルド一覧:"

#: musicbot/bot.py:2330 musicbot/bot.py:2356 musicbot/bot.py:8735
#, python-format
msgid " - %s"
msgstr " - %s"

#: musicbot/bot.py:2339
#, python-format
msgid "Left %s due to bot owner not found"
msgstr "ボット所有者が見つからないため、 %s を退出しました"

#: musicbot/bot.py:2344
#, python-format
msgid "Not proceeding with checks in %s servers due to unavailability"
msgstr "%s サーバーでのチェックが利用できません。"

#: musicbot/bot.py:2350
#, python-format
msgid "Owner could not be found on any guild (id: %s)\n"
msgstr ""

#: musicbot/bot.py:2359
msgid "Owner unknown, bot is not on any guilds."
msgstr "所有者は不明です。botはギルドにいません。"

#: musicbot/bot.py:2363
#, python-format
msgid ""
"To make the bot join a guild, paste this link in your browser. \n"
"Note: You should be logged into your main account and have \n"
"manage server permissions on the guild you want the bot to join.\n"
"  %s"
msgstr ""

#: musicbot/bot.py:2380
#, python-format
msgid "Got None for bound channel with ID:  %d"
msgstr "Got None for bound channel with ID:  %d"

#: musicbot/bot.py:2386
#, python-format
msgid "Cannot bind to non Messageable channel with ID:  %d"
msgstr "IDを持つメッセージ可能でないチャンネルにバインドできません:  %d"

#: musicbot/bot.py:2400
msgid "Bound to text channels:"
msgstr "Bound to text channels:"

#: musicbot/bot.py:2414 musicbot/bot.py:2464
#, python-format
msgid " - %(guild)s/%(channel)s"
msgstr " - %(guild)s/%(channel)s"

#: musicbot/bot.py:2418 musicbot/bot.py:2420
msgid "Not bound to any text channels"
msgstr "テキストチャンネルにバインドされていません"

#: musicbot/bot.py:2431
#, python-format
msgid "Got None for auto join channel with ID:  %d"
msgstr "IDを持つ自動参加チャンネルにNoneを取得しました:  %d"

#: musicbot/bot.py:2437
#, python-format
msgid "Cannot auto join a Private/Non-Guild channel with ID:  %d"
msgstr "IDを持つプライベート/非ギルドチャンネルに自動的に参加できません:  %d"

#: musicbot/bot.py:2445
#, python-format
msgid "Cannot auto join to non-connectable channel with ID:  %d"
msgstr "IDを持つ非接続可能なチャンネルに自動的に参加できません:  %d"

#: musicbot/bot.py:2461
msgid "Auto joining voice channels:"
msgstr "ボイスチャンネルの自動結合:"

#: musicbot/bot.py:2469 musicbot/bot.py:2472
msgid "Not auto joining any voice channels"
msgstr "音声チャンネルに自動的に参加しません"

#: musicbot/bot.py:2485
#, python-format
msgid ""
"Detected missing config options!\n"
"\n"
"Problem:\n"
"  You config options file is missing some options.\n"
"  Default settings will be used for these options.\n"
"  Here is a list of options we didn't find:\n"
"  %(missing)s\n"
"\n"
"Solution:\n"
"  Copy new options from the example options file.\n"
"  Or use the config command to set and save them.\n"
"\n"
msgstr ""

#: musicbot/bot.py:2514
#, python-format
msgid "Event on_ready has fired %s times"
msgstr "イベントon_ready が %s 回発射しました"

#: musicbot/bot.py:2530
msgid "Getting application info."
msgstr "アプリケーション情報を取得しています。"

#: musicbot/bot.py:2548
msgid "Ensuring data folders exist"
msgstr "データフォルダが存在することを確認"

#: musicbot/bot.py:2563
msgid "Validating config"
msgstr "設定を検証中"

#: musicbot/bot.py:2566
msgid "Validating permissions config"
msgstr "権限設定を検証中"

#: musicbot/bot.py:2576
msgid "Disabled"
msgstr "無効"

#: musicbot/bot.py:2576
msgid "Enabled"
msgstr "有効"

#: musicbot/bot.py:2579
msgid "Options:"
msgstr "オプション:"

#: musicbot/bot.py:2581
#, python-format
msgid "  Command prefix: %s"
msgstr "  コマンドプレフィックス: %s"

#: musicbot/bot.py:2582
#, python-format
msgid "  Default volume: %d%%"
msgstr "  デフォルトボリューム: %d%%"

#: musicbot/bot.py:2584
#, python-format
msgid "  Skip threshold: %(num)d votes or %(percent).0f%%"
msgstr "  Skip threshold: %(num)d vote or %(percent).0f%%"

#: musicbot/bot.py:2591
#, python-format
msgid "  Now Playing @mentions: %s"
msgstr "  現在@メンションを再生中: %s"

#: musicbot/bot.py:2594
#, python-format
msgid "  Auto-Summon: %s"
msgstr "  自動召喚: %s"

#: musicbot/bot.py:2596
#, python-format
msgid "  Auto-Playlist: %(status)s (order: %(order)s)"
msgstr "  自動プレイリスト: %(status)s (注文: %(order)s)"

#: musicbot/bot.py:2599
msgid "random"
msgstr "random"

#: musicbot/bot.py:2599
msgid "sequential"
msgstr "シーケンシャル"

#: musicbot/bot.py:2604
#, python-format
msgid "  Auto-Pause: %s"
msgstr "  自動停止: %s"

#: musicbot/bot.py:2606
#, python-format
msgid "  Delete Messages: %s"
msgstr "  メッセージの削除: %s"

#: musicbot/bot.py:2611
#, python-format
msgid "    Delete Invoking: %s"
msgstr "    呼び出しを削除: %s"

#: musicbot/bot.py:2615
#, python-format
msgid "    Delete Now Playing: %s"
msgstr "    今すぐプレイを削除: %s"

#: musicbot/bot.py:2618
#, python-format
msgid "  Debug Mode: %s"
msgstr "  デバッグモード: %s"

#: musicbot/bot.py:2620
#, python-format
msgid "  Downloaded songs will be %s"
msgstr "  ダウンロードした曲は %sになります"

#: musicbot/bot.py:2624
#, python-format
msgid "    Delete if unused for %d days"
msgstr "    %d 日間未使用の場合は削除"

#: musicbot/bot.py:2627
#, python-format
msgid "    Delete if size exceeds %s"
msgstr "    サイズが %s を超えた場合は削除"

#: musicbot/bot.py:2630
#, python-format
msgid "  Status message: %s"
msgstr "  ステータスメッセージ： %s"

#: musicbot/bot.py:2632
#, python-format
msgid "  Write current songs to file: %s"
msgstr "  現在の曲をファイルに書き込む: %s"

#: musicbot/bot.py:2636
#, python-format
msgid "  Author insta-skip: %s"
msgstr "  著者インスタジオスキップ: %s"

#: musicbot/bot.py:2639
#, python-format
msgid "  Embeds: %s"
msgstr "  Embeds: %s"

#: musicbot/bot.py:2641
#, python-format
msgid "  Spotify integration: %s"
msgstr "  Spotify統合: %s"

#: musicbot/bot.py:2644
#, python-format
msgid "  Legacy skip: %s"
msgstr "  従来のスキップ： %s"

#: musicbot/bot.py:2646
#, python-format
msgid "  Leave non owners: %s"
msgstr "  所有者ではないまま: %s"

#: musicbot/bot.py:2650
#, python-format
msgid "  Leave inactive VC: %s"
msgstr "  非アクティブ状態のままVC: %s"

#: musicbot/bot.py:2655
#, python-format
msgid "    Timeout: %s seconds"
msgstr "    タイムアウト: %s 秒"

#: musicbot/bot.py:2659
#, python-format
msgid "  Leave at song end/empty queue: %s"
msgstr "  曲の終了/空のキューを残す: %s"

#: musicbot/bot.py:2663
#, python-format
msgid "  Leave when player idles: %s"
msgstr "  プレイヤーがアイドル時に退出： %s"

#: musicbot/bot.py:2667
#, python-format
msgid "    Timeout: %d seconds"
msgstr "    タイムアウト: %d 秒"

#: musicbot/bot.py:2668
#, python-format
msgid "  Self Deafen: %s"
msgstr "  セルフスピーカー: %s"

#: musicbot/bot.py:2670
#, python-format
msgid "  Per-server command prefix: %s"
msgstr "  サーバー毎のコマンドプレフィックス: %s"

#: musicbot/bot.py:2673
#, python-format
msgid "  Search List: %s"
msgstr "  検索リスト： %s"

#: musicbot/bot.py:2675
#, python-format
msgid "  Round Robin Queue: %s"
msgstr "  ラウンドロビン隊列： %s"

#: musicbot/bot.py:2705
#, python-format
msgid "The requested song `%(subject)s` is blocked by the song block list."
msgstr "The requested song `%(subject)s` is blocked by the song block list."

#: musicbot/bot.py:2716
msgid ""
"Attempted to handle Voice Channel inactivity, but Bot is not in voice..."
msgstr "Voice Channel を操作しようとしていますが、Botは音声に入っていません..."

#: musicbot/bot.py:2723
#, python-format
msgid "Channel activity already waiting in guild: %s"
msgstr "ギルドで既に待機しているチャンネルアクティビティ： %s"

#: musicbot/bot.py:2733
#, python-format
msgid ""
"Channel activity waiting %(time)d seconds to leave channel: %(channel)s"
msgstr "チャンネルのアクティビティが %(time)d 秒でチャンネルを退出するまで待機しています: %(channel)s"

#: musicbot/bot.py:2748
#, python-format
msgid "Channel activity timer for %s has expired. Disconnecting."
msgstr "%s のチャネルアクティビティタイマーの有効期限が切れました。切断してください。"

#: musicbot/bot.py:2754
#, python-format
msgid "Channel activity timer canceled for: %(channel)s in %(guild)s"
msgstr "チャネルアクティビティのタイマーをキャンセルしました: %(channel)s の %(guild)s"

#: musicbot/bot.py:2782
#, python-format
msgid "Ignoring player inactivity in auto-joined channel:  %s"
msgstr "自動参加チャンネルのプレイヤーの非アクティブを無視:  %s"

#: musicbot/bot.py:2789
#, python-format
msgid "Player activity timer already waiting in guild: %s"
msgstr "ギルド内で既に待機しているプレイヤーアクティビティタイマー： %s"

#: musicbot/bot.py:2797
#, python-format
msgid ""
"Player activity timer waiting %(time)d seconds to leave channel: %(channel)s"
msgstr "%(time)d 秒でチャンネルを退出するのを待っているプレイヤーアクティビティタイマー: %(channel)s"

#: musicbot/bot.py:2809
#, python-format
msgid "Player activity timer for %s has expired. Disconnecting."
msgstr "%s のプレイヤーアクティビティタイマーの有効期限が切れています。切断してください。"

#: musicbot/bot.py:2815 musicbot/bot.py:2820
#, python-format
msgid "Player activity timer canceled for: %(channel)s in %(guild)s"
msgstr "プレイヤーアクティビティのタイマーを %(channel)s でキャンセルしました: %(guild)s"

#: musicbot/bot.py:2837
msgid "Player activity timer is being reset."
msgstr "プレイヤーアクティビティのタイマーがリセットされています。"

#: musicbot/bot.py:2950
msgid "No such command"
msgstr "そのようなコマンドはありません"

#: musicbot/bot.py:3026
msgid "You must mention a user or provide their ID number."
msgstr "ユーザーに言及するか、ID番号を入力してください。"

#: musicbot/bot.py:3031
msgid "Invalid sub-command given. Use `help blockuser` for usage examples."
msgstr "無効なサブコマンドが与えられました。使用例には `help blockuser` を使用してください。"

#: musicbot/bot.py:3042
msgid "MusicBot could not find the user(s) you specified."
msgstr "MusicBotは指定したユーザーを見つけることができませんでした。"

#: musicbot/bot.py:3049
msgid "The owner cannot be added to the block list."
msgstr "オーナーをブロックリストに追加できません。"

#: musicbot/bot.py:3053
#, python-format
msgid "Not adding user to block list, already blocked:  %(id)s/%(name)s"
msgstr "ユーザーをブロックリストに追加していません。既にブロックされています:  %(id)s/%(name)s"

#: musicbot/bot.py:3062
#, python-format
msgid "Not removing user from block list, not listed:  %(id)s/%(name)s"
msgstr "リストにないブロックリストからユーザーを削除していません:  %(id)s/%(name)s"

#: musicbot/bot.py:3079
msgid "Cannot add the users you listed, they are already added."
msgstr "あなたがリストしたユーザーを追加することはできません、すでに追加されています。"

#: musicbot/bot.py:3156
msgid "You must provide a song subject if no song is currently playing."
msgstr "現在再生中の曲がない場合は、曲の件名を指定する必要があります。"

#: musicbot/bot.py:3162
msgid "Invalid sub-command given. Use `help blocksong` for usage examples."
msgstr "無効なサブコマンドが与えられました。使用例には `help blocksong` を使用してください。"

#: musicbot/bot.py:3174
#, python-format
msgid "Subject `%(subject)s` is already in the song block list."
msgstr "Subject `%(subject)s` はすでにソングブロックリストにあります。"

#: musicbot/bot.py:3206
msgid "The subject is not in the song block list and cannot be removed."
msgstr "件名はソングブロックリストにないため、削除できません。"

#: musicbot/bot.py:3278
msgid "Invalid sub-command given. Use `help autoplaylist` for usage examples."
msgstr "無効なサブコマンドが与えられました。使用例には `help autoplaylist` を使用してください。"

#: musicbot/bot.py:3285
msgid "The supplied song link is invalid"
msgstr "指定された曲のリンクは無効です"

#: musicbot/bot.py:3291
msgid "The queue is empty. Add some songs with a play command!"
msgstr "キューが空です。再生コマンドで曲を追加してください！"

#: musicbot/bot.py:3319
msgid "This song is already in the autoplaylist."
msgstr "この曲はすでに自動プレイリストにあります。"

#: musicbot/bot.py:3336
msgid "This song is not yet in the autoplaylist."
msgstr "この曲はまだ自動プレイリストに入っていません。"

#: musicbot/bot.py:3370
msgid "You must provide a playlist filename."
msgstr "プレイリストファイル名を指定する必要があります。"

#: musicbot/bot.py:3480
msgid "You are not allowed to request playlists"
msgstr "プレイリストをリクエストする権限がありません"

#: musicbot/bot.py:3488
#, python-format
msgid "Playlist has too many entries (%(songs)s but max is %(max)s)"
msgstr "プレイリストのエントリが多すぎます(%(songs)s ですが、最大は %(max)s です)"

#: musicbot/bot.py:3499
#, python-format
msgid ""
"The playlist entries will exceed your queue limit.\n"
"There are %(songs)s in the list, and %(queued)s already in queue.\n"
"The limit is %(max)s for your group."
msgstr ""

#: musicbot/bot.py:3523
msgid "Ignoring auto-pause due to network outage."
msgstr "ネットワーク停止による自動停止を無視します。"

#: musicbot/bot.py:3528
msgid ""
"MusicPlayer has no VoiceClient or has no channel data, cannot process auto-"
"pause."
msgstr "MusicPlayerにVoiceClientがないか、チャンネルデータがないか、自動停止処理できません。"

#: musicbot/bot.py:3539
msgid "Already processing auto-pause, ignoring this event."
msgstr "このイベントを無視して、すでに自動一時停止を処理しています。"

#: musicbot/bot.py:3547
#, python-format
msgid ""
"%sVoiceClient not connected, waiting %s seconds to handle auto-pause in "
"guild:  %s"
msgstr "%sVoiceClient が接続されていないため、ギルド内の自動停止を処理する %s 秒待機しています:  %s"

#: musicbot/bot.py:3555
msgid "Auto-pause waiting was cancelled."
msgstr "自動一時停止はキャンセルされました。"

#: musicbot/bot.py:3562
msgid "A new MusicPlayer is being connected, ignoring old auto-pause event."
msgstr "古い自動一時停止イベントを無視して、新しいMusicPlayerが接続されています。"

#: musicbot/bot.py:3578
#, python-format
msgid "Playing in an empty voice channel, running auto pause for guild: %s"
msgstr "空のボイスチャンネルで再生します。ギルドの自動一時停止： %s"

#: musicbot/bot.py:3585
#, python-format
msgid "Previously auto paused player is unpausing for guild: %s"
msgstr "以前の自動一時停止中のプレイヤーはギルドの一時停止が解除されています: %s"

#: musicbot/bot.py:3816
msgid "Cannot use seek if there is nothing playing."
msgstr "何もプレイしていない場合はシークを使用できません。"

#: musicbot/bot.py:3821
msgid "Cannot use seek on current track, it has an unknown duration."
msgstr "現在のトラックでシークを使用することはできません、それは不明な期間を持っています。"

#: musicbot/bot.py:3827
msgid "Seeking is not supported for streams."
msgstr "Seeking is not supported for streams."

#: musicbot/bot.py:3837
msgid "Cannot use seek without a time to position playback."
msgstr "再生を配置する時間がなければシークは使用できません。"

#: musicbot/bot.py:3855
#, python-format
msgid "Could not convert `%(input)s` to a valid time in seconds."
msgstr "`%(input)s`を秒単位で有効な時間に変換できませんでした。"

#: musicbot/bot.py:3868
#, python-format
msgid ""
"Cannot seek to `%(input)s` (`%(seconds)s` seconds) in the current track with"
" a length of `%(progress)s / %(total)s`"
msgstr ""
"`%(input)s/%(seconds)s`の長さのトラックの`%(progress)s `（` %(total)s`秒）をシークできません"

#: musicbot/bot.py:3929
msgid "Invalid sub-command. Use the command `help repeat` for usage examples."
msgstr "無効なサブコマンドです。使用例には「ヘルプの繰り返し」コマンドを使用してください。"

#: musicbot/bot.py:3967
msgid "The player is not currently looping."
msgstr "プレーヤーは現在ループしていません。"

#: musicbot/bot.py:4023
msgid "Song positions must be integers!"
msgstr "曲の位置は整数でなければなりません！"

#: musicbot/bot.py:4028
msgid "You gave a position outside the playlist size!"
msgstr "プレイリストのサイズ以外の位置を指定しました！"

#: musicbot/bot.py:4077
msgid ""
"Could not prompt for playlist playback, no message to add reactions to."
msgstr "プレイリストの再生を促すことができませんでした。リアクションを追加するメッセージがありません。"

#: musicbot/bot.py:4166
msgid "Local media playback is not enabled."
msgstr "ローカルメディアの再生が有効になっていません。"

#: musicbot/bot.py:4207
msgid "Spotify URL is invalid or not currently supported."
msgstr "SpotifyのURLが無効または現在サポートされていません。"

#: musicbot/bot.py:4211
msgid "Detected a Spotify URL, but Spotify is not enabled."
msgstr "Spotify の URL が検出されましたが、Spotify は有効ではありません。"

#: musicbot/bot.py:4221 musicbot/bot.py:4426
#, python-format
msgid "You have reached your enqueued song limit (%(max)s)"
msgstr "キューに登録された曲の上限に達しました (%(max)s)"

#: musicbot/bot.py:4227 musicbot/bot.py:4432 musicbot/bot.py:4526
msgid "Karaoke mode is enabled, please try again when its disabled!"
msgstr "カラオケモードが有効になっています。無効になったらもう一度お試しください！"

#: musicbot/bot.py:4239
msgid "Issue with extract_info(): "
msgstr "extract_info() の問題: "

#: musicbot/bot.py:4243 musicbot/bot.py:4448
#, python-format
msgid ""
"Failed to extract info due to error:\n"
"%(raw_error)s"
msgstr ""
"エラーのための情報の抽出に失敗しました:\n"
"%(raw_error)s"

#: musicbot/bot.py:4249
msgid "That video cannot be played. Try using the stream command."
msgstr "動画を再生できません。streamコマンドを使用してみてください。"

#: musicbot/bot.py:4260
#, python-format
msgid "YouTube search returned no results for:  %(url)s"
msgstr "YouTubeの検索結果が  %(url)sにはありませんでした"

#: musicbot/bot.py:4290
#, python-format
msgid ""
"Processed %(number)d of %(total)d songs in %(time).3f seconds at "
"%(time_per).2f s/song"
msgstr ""

#: musicbot/bot.py:4301
#, python-format
msgid ""
"No songs were added, all songs were over max duration (%(max)s seconds)"
msgstr "曲が追加されていません。すべての曲が最大時間（%(max)s 秒）を超えています。"

#: musicbot/bot.py:4317
msgid "Extracted an entry with 'youtube:playlist' as extractor key"
msgstr "抽出キーとして 'youtube:playlist' でエントリを抽出しました"

#: musicbot/bot.py:4329
#, python-format
msgid "Song duration exceeds limit (%(length)s > %(max)s)"
msgstr "曲の再生時間が制限を超えています(%(length)s > %(max)s)"

#: musicbot/bot.py:4347
#, python-format
msgid "Added song(s) at position %s"
msgstr "%s位置に曲を追加しました"

#: musicbot/bot.py:4384
#, python-format
msgid "Cannot estimate time until playing for position: %d"
msgstr "位置の再生までの時間を見積もることはできません: %d"

#: musicbot/bot.py:4445
#, python-format
msgid "Failed to get info from the stream request: %s"
msgstr "ストリームリクエストからの情報の取得に失敗しました: %s"

#: musicbot/bot.py:4454
msgid "Streaming playlists is not yet supported."
msgstr "ストリーミングプレイリストはまだサポートされていません。"

#: musicbot/bot.py:4520
#, python-format
msgid "You have reached your playlist item limit (%(max)s)"
msgstr "プレイリストアイテムの上限に達しました (%(max)s)"

#: musicbot/bot.py:4532
msgid ""
"Please specify a search query.  Use `help search` for more information."
msgstr "検索クエリを指定してください。詳細は `ヘルプ検索` を使用してください。"

#: musicbot/bot.py:4561
#, python-format
msgid "You cannot search for more than %(max)s videos"
msgstr "%(max)s 以上の動画を検索することはできません"

#: musicbot/bot.py:4886
#, python-format
msgid "Waiting for summon lock: %s"
msgstr "召喚ロックを待っています： %s"

#: musicbot/bot.py:4889
#, python-format
msgid "Summon lock acquired for: %s"
msgstr "ロックを召喚: %s"

#: musicbot/bot.py:4893
msgid "You are not connected to voice. Try joining a voice channel!"
msgstr "音声に接続されていません。音声チャンネルに参加してみてください！"

#: musicbot/bot.py:4918
#, python-format
msgid "Joining %(guild)s/%(channel)s"
msgstr "%(guild)s/%(channel)s に参加中"

#: musicbot/bot.py:4980
msgid "MusicBot cannot follow a user that is not a member of the server."
msgstr "MusicBot はサーバーのメンバーではないユーザーをフォローできません。"

#: musicbot/bot.py:5008
msgid "Player is not playing."
msgstr "プレイヤーがプレイしていません。"

#: musicbot/bot.py:5133
msgid "Nothing in the queue to remove!"
msgstr "削除するキューがありません！"

#: musicbot/bot.py:5154
#, python-format
msgid "Nothing found in the queue from user `%(user)s`"
msgstr "`%(user)s`からのキューには何も見つかりませんでした。"

#: musicbot/bot.py:5159 musicbot/bot.py:5194
msgid ""
"You do not have the permission to remove that entry from the queue.\n"
"You must be the one who queued it or have instant skip permissions."
msgstr ""
"キューからそのエントリを削除する権限がありません。\n"
"キューに登録した方、または即座にスキップ権限を持っている必要があります。"

#: musicbot/bot.py:5170 musicbot/bot.py:5175
msgid "Invalid entry number. Use the queue command to find queue positions."
msgstr "無効なエントリ番号です。キューの位置を見つけるには、キューコマンドを使用してください。"

#: musicbot/bot.py:5225
msgid "Can't skip! The player is not playing!"
msgstr "スキップできません！プレイヤーがプレイしていません！"

#: musicbot/bot.py:5277
msgid "You do not have permission to force skip a looped song."
msgstr "ループされた曲をスキップする権限がありません。"

#: musicbot/bot.py:5296
msgid "You do not have permission to force skip."
msgstr "スキップを強制する権限がありません。"

#: musicbot/bot.py:5333 musicbot/bot.py:5366
msgid "You do not have permission to skip a looped song."
msgstr "ループ曲をスキップする権限がありません。"

#: musicbot/bot.py:5416
#, python-format
msgid "`%(new_volume)s` is not a valid number"
msgstr "'%(new_volume)s' は有効な数字ではありません"

#: musicbot/bot.py:5437
#, python-format
msgid ""
"Unreasonable volume change provided: %(old_volume)s%(adjustment)s is %(new_volume)s.\n"
"Volume can only be set from 1 to 100."
msgstr ""
"不合理なボリューム変更が提供されました: %(old_volume)s%(adjustment)s は %(new_volume)sです。\n"
"ボリュームは1から100まで設定できます。"

#: musicbot/bot.py:5447
#, python-format
msgid ""
"Unreasonable volume provided: %(volume)s. Provide a value between 1 and 100."
msgstr "不合理なボリュームが提供されました: %(volume)s. 1から100までの値を入力してください。"

#: musicbot/bot.py:5471
msgid ""
"No track is playing, cannot set speed.\n"
"Use the config command to set a default playback speed."
msgstr ""
"トラックが再生されていないため、速度を設定できません。\n"
"デフォルトの再生速度を設定するにはconfigコマンドを使用してください。"

#: musicbot/bot.py:5479
msgid "Speed cannot be applied to streamed media."
msgstr "ストリームメディアには速度を適用できません。"

#: musicbot/bot.py:5484
msgid "You must provide a speed to set."
msgstr "設定する速度を提供する必要があります。"

#: musicbot/bot.py:5493
msgid "The speed you provided is invalid. Use a number between 0.5 and 100."
msgstr "指定した速度が無効です。0.5 から 100までの数字を使用してください。"

#: musicbot/bot.py:5552 musicbot/bot.py:5668 musicbot/bot.py:6598
#, python-format
msgid "Invalid option for command: `%(option)s`"
msgstr "コマンドの無効なオプション: `%(option)s`"

#: musicbot/bot.py:5566
#, python-format
msgid ""
"Failed to save aliases due to error:\n"
"`%(raw_error)s`"
msgstr ""
"エラーのためエイリアスを保存できませんでした:\n"
"`%(raw_error)s`"

#: musicbot/bot.py:5573
msgid "You must supply an alias and a command to alias"
msgstr "エイリアスにエイリアスとコマンドを提供する必要があります"

#: musicbot/bot.py:5588
msgid "You must supply an alias name to remove."
msgstr "削除するにはエイリアス名を入力してください。"

#: musicbot/bot.py:5593
#, python-format
msgid "The alias `%(alias)s` does not exist."
msgstr "The alias `%(alias)s` does not exist."

#: musicbot/bot.py:5651
msgid "Config cannot use channel and user mentions at the same time."
msgstr "設定では、チャンネルとユーザーのメンションを同時に使用できません。"

#: musicbot/bot.py:5754
#, python-format
msgid ""
"Unable to reload Config due to the following error:\n"
"%(raw_error)s"
msgstr ""
"次のエラーのため設定を再読み込みできません:\n"
"%(raw_error)s"

#: musicbot/bot.py:5772
msgid ""
"Could not resolve section name from option name. Please provide a valid "
"section and option name."
msgstr "オプション名からセクション名を解決できませんでした。有効なセクション名とオプション名を入力してください。"

#: musicbot/bot.py:5776
msgid "The option given is ambiguous, please provide a section name."
msgstr "与えられたオプションは曖昧です。セクション名を入力してください。"

#: musicbot/bot.py:5782
msgid "You must provide a section name and option name for this command."
msgstr "このコマンドのセクション名とオプション名を指定する必要があります。"

#: musicbot/bot.py:5798
#, python-format
msgid ""
"The section `%(section)s` is not available.\n"
"The available sections are:  %(sections)s"
msgstr ""
"The section `%(section)s` is not available.\n"
"The available section:  %(sections)s"

#: musicbot/bot.py:5806
#, python-format
msgid "The option `%(option)s` is not available."
msgstr "オプション `%(option)s` は使用できません。"

#: musicbot/bot.py:5834
#, python-format
msgid "Option `%(option)s` is not editable. Cannot save to disk."
msgstr "オプション `%(option)s` は編集できません。ディスクに保存できません。"

#: musicbot/bot.py:5843
#, python-format
msgid "Failed to save the option:  `%(option)s`"
msgstr "オプションの保存に失敗しました: `%(option)s`"

#: musicbot/bot.py:5858
#, python-format
msgid "Option `%(option)s` is not editable, value cannot be displayed."
msgstr "Option `%(option)s` は編集できません。値を表示できません。"

#: musicbot/bot.py:5881
#, python-format
msgid "Option `%(option)s` is not editable. Cannot update setting."
msgstr "オプション `%(option)s` は編集できません。設定を更新できません。"

#: musicbot/bot.py:5887 musicbot/bot.py:6811
msgid "You must provide a section, option, and value for this sub command."
msgstr "このサブコマンドのセクション、オプション、値を指定する必要があります。"

#: musicbot/bot.py:5891
#, python-format
msgid "Doing set with on %(config)s == %(value)s"
msgstr "%(config)s == %(value)s で設定する"

#: musicbot/bot.py:5898
#, python-format
msgid "Option `%(option)s` was not updated!"
msgstr "Option `%(option)s` は更新されませんでした！"

#: musicbot/bot.py:5914
#, python-format
msgid "Option `%(option)s` is not editable. Cannot reset to default."
msgstr "オプション `%(option)s` は編集できません。デフォルトにリセットできません。"

#: musicbot/bot.py:5926
#, python-format
msgid "Resetting %(config)s to default %(value)s"
msgstr "%(config)s を既定の %(value)s にリセット"

#: musicbot/bot.py:5933
#, python-format
msgid "Option `%(option)s` was not reset to default!"
msgstr "Option `%(option)s` はデフォルトにリセットされませんでした！"

#: musicbot/bot.py:5966
msgid "The option command is deprecated, use the config command instead."
msgstr "option コマンドは推奨されません。config コマンドを使用してください。"

#: musicbot/bot.py:5986
msgid "Invalid option specified, use: info, update, or clear"
msgstr "無効なオプションが指定されました。情報、更新、またはクリアを使用してください。"

#: musicbot/bot.py:6043
msgid "**Failed** to delete cache, check logs for more info..."
msgstr "**キャッシュの削除に失敗しました。ログの詳細を確認してください。"

#: musicbot/bot.py:6078
msgid "Queue page argument must be a whole number."
msgstr "キューページ引数は整数でなければなりません。"

#: musicbot/bot.py:6085
msgid "There are no songs queued! Queue something with a play command."
msgstr "曲がキューに追加されていません! playコマンドで何かをキューに追加します。"

#: musicbot/bot.py:6092
#, python-format
msgid ""
"Requested page number is out of bounds.\n"
"There are **%(total)s** pages."
msgstr ""
"要求されたページ番号が範囲外です。\n"
"**%(total)s** ページがあります。"

#: musicbot/bot.py:6135
msgid "Skipped the current playlist entry."
msgstr "現在のプレイリストのエントリをスキップしました。"

#: musicbot/bot.py:6178
msgid "Not enough entries to paginate the queue."
msgstr "キューをページネーションするのに十分なエントリがありません。"

#: musicbot/bot.py:6182
msgid "Could not post queue message, no message to add reactions to."
msgstr "キューメッセージを投稿できませんでした。リアクションを追加するメッセージがありません。"

#: musicbot/bot.py:6184
msgid ""
"Try that again. MusicBot couldn't make or get a reference to the queue message.\n"
"If the issue persists, file a bug report."
msgstr ""
"もう一度お試しください。MusicBotはキューメッセージへの参照を作成できませんでした。\n"
"問題が解決しない場合は、バグレポートを送信してください。"

#: musicbot/bot.py:6294
msgid "Cannot use purge on private DM channel."
msgstr "プライベート DM チャンネルでパージを使用できません。"

#: musicbot/bot.py:6326
msgid "The given URL was not a valid URL."
msgstr "指定されたURLは有効なURLではありませんでした。"

#: musicbot/bot.py:6336
#, python-format
msgid ""
"Could not extract info from input url\n"
"%(raw_error)s\n"
msgstr ""

#: musicbot/bot.py:6341
msgid "This does not seem to be a playlist."
msgstr "これはプレイリストではないようです。"

#: musicbot/bot.py:6504
msgid ""
"Invalid user ID or server nickname, please double-check the ID and try "
"again."
msgstr "無効なユーザーIDまたはサーバーニックネームです。IDを再確認してもう一度やり直してください。"

#: musicbot/bot.py:6511
msgid "Could not determine the discord User.  Try again."
msgstr "discordユーザーを特定できませんでした。もう一度お試しください。"

#: musicbot/bot.py:6582
msgid "Permissions cannot use channel and user mentions at the same time."
msgstr "権限は同時にチャンネルとユーザーメンションを使用することはできません。"

#: musicbot/bot.py:6617
#, python-format
msgid ""
"Unable to reload Permissions due to an error:\n"
"%(raw_error)s"
msgstr ""
"エラーが発生したため権限を再読み込みできません:\n"
"%(raw_error)s"

#: musicbot/bot.py:6654
msgid "You must provide a group or option name for this command."
msgstr "このコマンドのグループまたはオプション名を指定する必要があります。"

#: musicbot/bot.py:6658
msgid "You must provide a group, option, and value to set for this command."
msgstr "このコマンドに設定するには、グループ、オプション、値を指定する必要があります。"

#: musicbot/bot.py:6672
#, python-format
msgid "The %(option)s sub-command requires a group and permission name."
msgstr "%(option)s サブコマンドにはグループ名と権限名が必要です。"

#: musicbot/bot.py:6684
#, python-format
msgid ""
"The group `%(group)s` is not available.\n"
"The available groups are:  %(sections)s"
msgstr ""
"The group `%(group)s` is not available.\n"
"The available groups is :  %(sections)s"

#: musicbot/bot.py:6695
#, python-format
msgid "The permission `%(option)s` is not available."
msgstr "パーミッション`%(option)s`は利用できません。"

#: musicbot/bot.py:6731
#, python-format
msgid "Cannot add group `%(group)s` it already exists."
msgstr "グループを追加できません`%(group)s` が既に存在します。"

#: musicbot/bot.py:6749
msgid "Cannot remove built-in group."
msgstr "組み込みグループを削除できません。"

#: musicbot/bot.py:6767 musicbot/bot.py:6806
msgid "The owner group is not editable."
msgstr "オーナーグループは編集できません。"

#: musicbot/bot.py:6775
#, python-format
msgid "Failed to save the group:  `%(group)s`"
msgstr "グループの保存に失敗しました: `%(group)s`"

#: musicbot/bot.py:6815
#, python-format
msgid "Doing set on %(option)s with value: %(value)s"
msgstr "%(option)s に値： %(value)s を設定する"

#: musicbot/bot.py:6822
#, python-format
msgid "Permission `%(option)s` was not updated!"
msgstr "パーミッション`%(option)s`は更新されませんでした！"

#: musicbot/bot.py:6863
msgid ""
"Failed to change username. Did you change names too many times?\n"
"Remember name changes are limited to twice per hour.\n"
msgstr ""
"ユーザー名の変更に失敗しました。名前の変更回数が多すぎましたか？\n"
"名前の変更は1時間に2回に制限されています。\n"

#: musicbot/bot.py:6869
#, python-format
msgid ""
"Failed to change username due to error:  \n"
"%(raw_error)s"
msgstr ""
"エラーのためユーザー名を変更できませんでした:  \n"
"%(raw_error)s"

#: musicbot/bot.py:6891
msgid "Unable to change nickname: no permission."
msgstr "ニックネームを変更できません: 権限がありません。"

#: musicbot/bot.py:6899
#, python-format
msgid ""
"Failed to set nickname due to error:  \n"
"%(raw_error)s"
msgstr ""
"エラーのためニックネームを設定できませんでした:  \n"
"%(raw_error)s"

#: musicbot/bot.py:6939
msgid "Custom emoji must be from this server to use as a prefix."
msgstr "プレフィックスとして使用するには、このサーバーからカスタム絵文字を使用する必要があります。"

#: musicbot/bot.py:6956
msgid ""
"Prefix per server is not enabled!\n"
"Use the config command to update the prefix instead."
msgstr ""
"サーバーごとのプレフィックスが有効になっていません!\n"
"configコマンドを使用して、代わりにプレフィックスを更新してください。"

#: musicbot/bot.py:6986
msgid "This command can only be used in guilds."
msgstr "このコマンドはギルドでのみ使用できます。"

#: musicbot/bot.py:6991
msgid "Invalid sub-command given. Use the help command for more information."
msgstr "指定された無効なサブコマンドです。詳細についてはヘルプコマンドを使用してください。"

#: musicbot/bot.py:7012
#, python-format
msgid "Cannot set language to `%(locale)s` it is not available."
msgstr "言語を`%(locale)s`に設定できません。利用できません。"

#: musicbot/bot.py:7057
msgid "You must provide a URL or attach a file."
msgstr "URLを入力するか、ファイルを添付する必要があります。"

#: musicbot/bot.py:7067
#, python-format
msgid ""
"Unable to change avatar due to error:  \n"
"%(raw_error)s"
msgstr ""
"エラーのためアバターを変更できません:  \n"
"%(raw_error)s"

#: musicbot/bot.py:7092
#, python-format
msgid "MusicBot found a %s with no guild!  This could be a problem."
msgstr "MusicBotはギルドのない %s を見つけました！問題が発生する可能性があります。"

#: musicbot/bot.py:7104
#, python-format
msgid "Not currently connected to server `%(guild)s`"
msgstr "現在サーバーに接続されていません `%(guild)s`"

#: musicbot/bot.py:7145
msgid ""
"Invalid option given, use one of:  soft, full, upgrade, uppip, or upgit"
msgstr "無効なオプションが与えられました。ソフト、フル、アップグレード、uppip、またはupgitのいずれかを使用してください"

#: musicbot/bot.py:7254
msgid "You must provide an ID or name."
msgstr "IDまたは名前を入力してください。"

#: musicbot/bot.py:7265
#, python-format
msgid "No guild was found with the ID or name `%(input)s`"
msgstr "IDまたは名前のギルドが見つかりませんでした。`%(input)s`"

#: musicbot/bot.py:7322
#, python-format
msgid "Activating debug breakpoint ID: %(uuid)s"
msgstr "デバッグブレークポイントIDをアクティベート中: %(uuid)s"

#: musicbot/bot.py:7362
msgid "Could not import `objgraph`, is it installed?"
msgstr "`objgraph` をインポートできませんでした。インストールされていますか？"

#: musicbot/bot.py:7437
msgid "Debug code ran with eval()."
msgstr "eval() で実行されたデバッグコード。"

#: musicbot/bot.py:7447
msgid "Debug code ran with exec()."
msgstr "exec()でデバッグコードを実行しました。"

#: musicbot/bot.py:7450
msgid "Debug code failed to execute."
msgstr "デバッグコードの実行に失敗しました。"

#: musicbot/bot.py:7452
#, python-format
msgid ""
"Failed to execute debug code:\n"
"%(py_code)s\n"
"Exception: ```\n"
"%(ex_name)s:\n"
"%(ex_text)s```"
msgstr ""
"デバッグコードの実行に失敗しました:\n"
"%(py_code)s\n"
"例外: ```\n"
"%(ex_name)s:\n"
"%(ex_text)s```"

#: musicbot/bot.py:7487 musicbot/bot.py:7548
#, python-format
msgid "Sub-command must be one of: %(options)s"
msgstr "サブコマンドは次のいずれかでなければなりません： %(options)s"

#: musicbot/bot.py:7587
msgid "Could not locate git executable."
msgstr "git 実行可能ファイルが見つかりませんでした。"

#: musicbot/bot.py:7631
msgid "Failed while checking for updates via git command."
msgstr "git コマンドで更新の確認に失敗しました。"

#: musicbot/bot.py:7660
msgid "Package missing meta in pip report."
msgstr "pipレポートにメタが見つからないパッケージ。"

#: musicbot/bot.py:7674
msgid "Failed to get pip update status due to some error."
msgstr "エラーが発生したため、Pip の更新ステータスを取得できませんでした。"

#: musicbot/bot.py:7734
msgid "Got a strange voice client entry."
msgstr "変なボイスクライアントのエントリがあります。"

#: musicbot/bot.py:7836
msgid "Cookies already enabled."
msgstr "クッキーは既に有効になっています。"

#: musicbot/bot.py:7843
msgid "Cookies must be uploaded to be enabled. (Missing cookies file.)"
msgstr "クッキーを有効にするには、アップロードする必要があります。"

#: musicbot/bot.py:7856
#, python-format
msgid "Could not enable cookies due to error:  %(raw_error)s"
msgstr "エラーのためクッキーを有効にできませんでした:  %(raw_error)s"

#: musicbot/bot.py:7870
#, python-format
msgid ""
"Could not rename cookies file due to error:  %(raw_error)s\n"
"Cookies temporarily disabled and will be re-enabled on next restart."
msgstr ""
"エラーのためクッキーファイルの名前を変更できませんでした:  %(raw_error)s\n"
"クッキーは一時的に無効化され、次回の再起動時に再度有効になります。"

#: musicbot/bot.py:7879
msgid ""
"No attached uploads were found, try again while uploading a cookie file."
msgstr "添付されたアップロードが見つかりませんでした。Cookie ファイルのアップロード中に再試行してください。"

#: musicbot/bot.py:7888
#, python-format
msgid "Could not remove old, disabled cookies file:  %(raw_error)s"
msgstr "古い無効化されたCookieファイルを削除できませんでした:  %(raw_error)s"

#: musicbot/bot.py:7897
#, python-format
msgid "Error downloading the cookies file from discord:  %(raw_error)s"
msgstr "discordからCookieファイルをダウンロード中にエラーが発生しました:  %(raw_error)s"

#: musicbot/bot.py:7902
#, python-format
msgid "Could not save cookies to disk:  %(raw_error)s"
msgstr "ディスクにクッキーを保存できませんでした:  %(raw_error)s"

#: musicbot/bot.py:7920
#, python-format
msgid "Got a message with no channel, somehow:  %s"
msgstr "チャンネルがないメッセージがあります。  %s"

#: musicbot/bot.py:7948
#, python-format
msgid "Ignoring command from myself (%s)"
msgstr "自分からのコマンドを無視しました (%s)"

#: musicbot/bot.py:7956
#, python-format
msgid "Ignoring command from other bot (%s)"
msgstr "他のボットからコマンドを無視しました (%s)"

#: musicbot/bot.py:7964
#, python-format
msgid "Ignoring command from channel of type:  %s"
msgstr "%s のチャンネルからコマンドを無視しました"

#: musicbot/bot.py:8048
#, python-format
msgid "User in block list: %(id)s/%(name)s  tried command: %(command)s"
msgstr "ブロックリストのユーザー: %(id)s/%(name)s  tried command: %(command)s"

#: musicbot/bot.py:8055
#, python-format
msgid "Message from %(id)s/%(name)s: %(message)s"
msgstr "%(id)s/%(name)sからのメッセージ : %(message)s"

#: musicbot/bot.py:8089
#, python-format
msgid "This command is not allowed for your permissions group:  %(group)s"
msgstr "このコマンドは権限グループには許可されていません：  %(group)s"

#: musicbot/bot.py:8124
msgid "This command requires you to be in a Voice channel."
msgstr "このコマンドを使用するには、ボイスチャンネルに参加する必要があります。"

#: musicbot/bot.py:8208
#, python-format
msgid "Invalid command usage, missing values for params: %(params)r"
msgstr "無効なコマンド使用法、パラメータの値がありません: %(params)r"

#: musicbot/bot.py:8250
#, python-format
msgid "Error in %(command)s: %(err_name)s: %(err_text)s"
msgstr "%(command)sのエラー : %(err_name)s: %(err_text)s"

#: musicbot/bot.py:8274
#, python-format
msgid "Exception while handling command: %(command)s"
msgstr "コマンド処理中の例外: %(command)s"

#: musicbot/bot.py:8306
#, python-format
msgid "Cannot generate help for missing command:  %s"
msgstr "不足しているコマンドのヘルプを生成できません:  %s"

#: musicbot/bot.py:8310
#, python-format
msgid "Missing help data for command:  %s"
msgstr "コマンドのヘルプデータがありません:  %s"

#: musicbot/bot.py:8427
#, python-format
msgid "Leaving voice channel %s in %s due to inactivity."
msgstr "%s に音声チャンネル %s を退出しています。"

#: musicbot/bot.py:8436
msgid "MusicBot has become connected."
msgstr "MusicBot が接続されました。"

#: musicbot/bot.py:8440
msgid "MusicBot has become disconnected."
msgstr "MusicBotの接続が切断されました。"

#: musicbot/bot.py:8445
#, python-format
msgid "Got a Socket Event:  %s"
msgstr "ソケットイベントがあります:  %s"

#: musicbot/bot.py:8461
msgid "VoiceState updated before on_ready finished"
msgstr "VoiceState は、on_readyが終了する前に更新されました"

#: musicbot/bot.py:8474
#, python-format
msgid "Ignoring %s in %s as it is a bound voice channel."
msgstr "%s の %s を無視しました。音声チャンネルです。"

#: musicbot/bot.py:8483
#, python-format
msgid "%s has been detected as empty. Handling timeouts."
msgstr "%s は空として検出されました。処理のタイムアウト。"

#: musicbot/bot.py:8494
#, python-format
msgid "A user joined %s, cancelling timer."
msgstr "ユーザーが %sに参加し、タイマーをキャンセルしました。"

#: musicbot/bot.py:8507
#, python-format
msgid ""
"The bot got moved and the voice channel %s is empty. Handling timeouts."
msgstr "ボットが移動され、音声チャンネル %s が空です。タイムアウトを処理します。"

#: musicbot/bot.py:8516
#, python-format
msgid "The bot got moved and the voice channel %s is not empty."
msgstr "ボットが移動され、音声チャンネル %s が空ではありません。"

#: musicbot/bot.py:8565
#, python-format
msgid "No longer following user %s"
msgstr "ユーザー %sをフォローしていません"

#: musicbot/bot.py:8587
#, python-format
msgid "Following user `%(user)s` to channel:  %(channel)s"
msgstr "次のユーザー`%(user)s`チャンネル:  %(channel)s"

#: musicbot/bot.py:8607
msgid "VoiceState disconnect before.channel is None."
msgstr "VoiceState disconnection.channel is None."

#: musicbot/bot.py:8634
#, python-format
msgid ""
"Disconnected from voice by Discord API in: %(guild)s/%(channel)s (Code: "
"%(code)s) [S:%(state)s]"
msgstr ""
"Discordによる音声から切断されました: %(guild)s/%(channel)s (コード: %(code)s) [S:%(state)s]"

#: musicbot/bot.py:8656
#, python-format
msgid "Cannot use auto-join channel with type: %(type)s  in guild:  %(guild)s"
msgstr "タイプの自動参加チャンネルは使用できません: ギルドの %(type)s  :  %(guild)s"

#: musicbot/bot.py:8663
#, python-format
msgid "Cannot find the auto-joined channel, was it deleted?  Guild:  %s"
msgstr "自動参加チャンネルが見つかりません。削除されましたか? ギルド:  %s"

#: musicbot/bot.py:8669
#, python-format
msgid "Reconnecting to auto-joined guild on channel:  %s"
msgstr "チャンネルのギルド自動参加に再接続中:  %s"

#: musicbot/bot.py:8682
#, python-format
msgid "Cannot auto join channel:  %s"
msgstr "チャンネルに自動参加できません:  %s"

#: musicbot/bot.py:8698
#, python-format
msgid "Bot has been added to guild: %s"
msgstr "Botがギルドに追加されました： %s"

#: musicbot/bot.py:8710
#, python-format
msgid "Left guild '%s' due to bot owner not found."
msgstr "ボット所有者が見つからないため、ギルド「%s」を退出しました。"

#: musicbot/bot.py:8724
#, python-format
msgid "Creating data folder for guild %s"
msgstr "ギルド %sのデータフォルダを作成しています"

#: musicbot/bot.py:8732
#, python-format
msgid "Bot has been removed from guild: %s"
msgstr "Botがギルドから削除されました: %s"

#: musicbot/bot.py:8733
msgid "Updated guild list:"
msgstr "更新されたギルドリスト:"

#: musicbot/bot.py:8748
#, python-format
msgid "Guild \"%s\" has become available."
msgstr "ギルド「%s」が利用可能になりました。"

#: musicbot/bot.py:8754
#, python-format
msgid "Resuming player in \"%s\" due to availability."
msgstr "空き状況により \"%s\" のプレイヤーを再開しています。"

#: musicbot/bot.py:8771
#, python-format
msgid "Guild \"%s\" has become unavailable."
msgstr "ギルド「%s」は利用できなくなりました。"

#: musicbot/bot.py:8777
#, python-format
msgid "Pausing player in \"%s\" due to unavailability."
msgstr "「%s」でプレイヤーを一時停止しています。"

#: musicbot/bot.py:8793
#, python-format
msgid "Guild update for:  %s"
msgstr "ギルド更新:  %s"

#: musicbot/bot.py:8799
#, python-format
msgid "Guild attribute %(attr)s is now: %(new)s  -- Was: %(old)s"
msgstr "Guild 属性 %(attr)s が現在: %(new)s  -- Was: %(old)s"

#: musicbot/bot.py:8831
#, python-format
msgid "Channel update for:  %(channel)s  --  %(changes)s"
msgstr "チャンネル更新:  %(channel)s  --  %(changes)s"

#: musicbot/config.py:87
#, python-format
msgid "Creating %s"
msgstr "%s の作成"

#: musicbot/config.py:108
#, python-format
msgid "Loading config from:  %s"
msgstr "%s から設定を読み込んでいます"

#: musicbot/config.py:1108
#, python-format
msgid ""
"Error while reading config.\n"
"\n"
"Problem:\n"
"  One or more required config option sections are missing.\n"
"  The missing sections are:\n"
"  %(sections)s\n"
"\n"
"Solution:\n"
"  Repair your config options file.\n"
"  Each [Section] must appear only once, with no other text on the same line.\n"
"  Each section must have at least one option.\n"
"  Use the example options as a template or copy it from the repository."
msgstr ""

#: musicbot/config.py:1138
#, python-format
msgid ""
"Cannot store more than %s log files. Option LogsMaxKept will be limited "
"instead."
msgstr "%s ログファイル以上を保存できません。オプションの LogsMaxKept は代わりに制限されます。"

#: musicbot/config.py:1146
msgid ""
"Config option LogsDateFormat is empty and this will break log file rotation."
" Using default instead."
msgstr "ConfigオプションLogsDateFormatは空で、ログファイルのローテーションが壊れます。代わりにデフォルトを使用します。"

#: musicbot/config.py:1157
msgid ""
"Error while validating config options.\n"
"\n"
"Problem:\n"
"  Config option AudioCachePath is not a directory.\n"
"\n"
"Solution:\n"
"  Make sure the path you configured is a path to a folder / directory."
msgstr ""

#: musicbot/config.py:1174
msgid "An exception was thrown while validating AudioCachePath."
msgstr "AudioCachePath の検証中に例外がスローされました。"

#: musicbot/config.py:1178
#, python-format
msgid ""
"Error while validating config options.\n"
"\n"
"Problem:\n"
"  AudioCachePath config option could not be set due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Double check the setting is a valid, accessible directory path."
msgstr ""
"設定オプションの検証中にエラーが発生しました。\n"
"\n"
"問題:\n"
"  AudioCachePath 設定オプションはエラーが原因で設定できませんでした:\n"
"  %(raw_error)s\n"
"\n"
"ソリューション:\n"
"  設定が有効であることを再確認してください。 アクセス可能なディレクトリパス"

#: musicbot/config.py:1190
#, python-format
msgid "Audio Cache will be stored in:  %s"
msgstr "オーディオキャッシュは  %sに保存されます"

#: musicbot/config.py:1201
#, python-format
msgid ""
"Error while reading config options.\n"
"\n"
"Problem:\n"
"  No bot Token was specified in the config options or environment.\n"
"\n"
"Solution:\n"
"  Set the Token config option or set environment variable %(env_var)s with an App token."
msgstr ""

#: musicbot/config.py:1222
msgid ""
"StatusMessage config option is too long, it will be limited to 128 "
"characters."
msgstr "StatusMessage 設定オプションが長すぎます。128 文字に制限されます。"

#: musicbot/config.py:1231
#, python-format
msgid ""
"The default playback speed must be between 0.5 and 100.0. The option value "
"of %.3f will be limited instead."
msgstr "デフォルトの再生速度は0.5から100.0の間でなければなりません。 %.3f のオプション値は制限されます。"

#: musicbot/config.py:1241
msgid ""
"Cookies TXT file detected. MusicBot will pass them to yt-dlp.\n"
"Cookies are not recommended, may not be supported, and may totally break.\n"
"Copying cookies from your web-browser risks exposing personal data and \n"
"in the best case can result in your accounts being banned!\n"
"\n"
"You have been warned!  Good Luck!  \\U0001F596\n"
msgstr ""

#: musicbot/config.py:1259
msgid "Validating options with service data..."
msgstr "サービスデータを使用してオプションを検証しています..."

#: musicbot/config.py:1265
msgid "Acquired owner ID via API"
msgstr "API経由で取得した所有者ID"

#: musicbot/config.py:1269
msgid ""
"Error while fetching 'OwnerID' automatically.\n"
"\n"
"Problem:\n"
"  Discord App info is not available.\n"
"  This could be a temporary API outage or a bug.\n"
"\n"
"Solution:\n"
"  Manually set the 'OwnerID' config option or try again later."
msgstr ""

#: musicbot/config.py:1281
msgid "MusicBot does not have a user instance, cannot proceed."
msgstr "MusicBotにユーザーインスタンスがありません。続行できません。"

#: musicbot/config.py:1287
msgid ""
"Error validating config options.\n"
"\n"
"Problem:\n"
"  The 'OwnerID' config is the same as your Bot / App ID.\n"
"\n"
"Solution:\n"
"  Do not use the Bot or App ID in the 'OwnerID' field."
msgstr ""

#: musicbot/config.py:1311
msgid "Config options file not found. Checking for alternatives..."
msgstr "設定オプションファイルが見つかりません。選択肢を確認しています..."

#: musicbot/config.py:1324
#, python-format
msgid ""
"Renaming %(ini_file)s to %(option_file)s, you should probably turn file "
"extensions on."
msgstr "%(ini_file)s を %(option_file)sにリネームするには、おそらくファイル拡張子を ON にする必要があります。"

#: musicbot/config.py:1332
#, python-format
msgid "Copying existing example options file:  %(example_file)s"
msgstr "既存のオプションファイルのコピー:  %(example_file)s"

#: musicbot/config.py:1346
msgid "Something went wrong while trying to find a config option file."
msgstr "設定オプションファイルの検索中に問題が発生しました。"

#: musicbot/config.py:1350
#, python-format
msgid ""
"Error locating config.\n"
"\n"
"Problem:\n"
"  Could not find or create a config file due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Verify the config folder and files exist and can be read by MusicBot."
msgstr ""
"設定の場所を特定できませんでした。\n"
"\n"
"問題:\n"
"  エラーが原因で設定ファイルを見つけることができませんでした:\n"
"  %(raw_error)s\n"
"\n"
"ソリューション:\n"
"  設定フォルダとファイルが存在することを確認し、MusicBotによって読み込まれます。"

#: musicbot/config.py:1368
#, python-format
msgid ""
"Error loading config.\n"
"\n"
"Problem:\n"
"  MusicBot could not read config file due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure the file is accessible and error free.\n"
"  Copy the example file from the repo if all else fails."
msgstr ""

#: musicbot/config.py:1392
msgid "Dev Bug! Config option has getter that is not available."
msgstr "Dev Bug! 設定オプションは利用できないゲッターがあります。"

#: musicbot/config.py:1397
msgid ""
"Dev Bug! Config option has invalid type, getter and default must be the same"
" type."
msgstr "Dev Bug! Config オプションは無効な型、getter とデフォルトは同じ型でなければなりません。"

#: musicbot/config.py:1417
msgid "Option was missing previously."
msgstr "オプションは以前に存在しませんでした。"

#: musicbot/config.py:1432
#, python-format
msgid "Config section not in parsed config! Missing: %s"
msgstr "パースされた設定セクションに設定セクションがありません! ミス: %s"

#: musicbot/config.py:1437
#, python-format
msgid "Saved config option: %(config)s  =  %(value)s"
msgstr "保存された設定オプション: %(config)s  =  %(value)s"

#: musicbot/config.py:1450
#, python-format
msgid "Failed to save config:  %s"
msgstr "設定を保存できませんでした:  %s"

#: musicbot/config.py:1955
msgid ""
"Option names are not unique between INI sections!  Resolver is disabled."
msgstr "オプション名はINIセクション間で一意ではありません! リゾルバーは無効です。"

#: musicbot/config.py:2123 musicbot/permissions.py:889
#, python-format
msgid "Failed to save default INI file at:  %s"
msgstr "デフォルトのINIファイルを  %sに保存できませんでした"

#: musicbot/config.py:2213
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  The owner ID in [%(section)s] > %(option)s is not valid.\n"
"\n"
"Solution:\n"
"  Set %(option)s to a numerical ID or set it to `auto` or `0` for automatic owner binding."
msgstr ""

#: musicbot/config.py:2249
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  The config option [%(section)s] > %(option)s is not a valid file location.\n"
"\n"
"Solution:\n"
"  Check the path setting and make sure the file exists and is accessible to MusicBot."
msgstr ""

#: musicbot/config.py:2279
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  One of the IDs in option [%(section)s] > %(option)s is invalid.\n"
"\n"
"Solution:\n"
"  Ensure all IDs are numerical, and separated only by spaces or commas."
msgstr ""

#: musicbot/config.py:2315
#, python-format
msgid ""
"Invalid DebugLevel option \"%(value)s\" given, falling back to level: "
"%(fallback)s"
msgstr "レベルに戻ります:%(value)s\"が無効です: %(fallback)s"

#: musicbot/config.py:2336
#, python-format
msgid ""
"Option [%(section)s] > %(option)s has invalid config value '%(value)s' using"
" default instead."
msgstr ""
"Option [%(section)s] > %(option)s has invalid config value '%(value)s' using"
" default instead."

#: musicbot/config.py:2385
#, python-format
msgid ""
"Option [%(section)s] > %(option)s has a value greater than 100 %% "
"(%(value)s) and will be set to %(fallback)s instead."
msgstr ""
"オプション [%(section)s] > %(option)s は 100 %% (%(value)s) より大きい値を持ち、代わりに "
"%(fallback)s に設定されます。"

#: musicbot/config.py:2469
#, python-format
msgid ""
"Renaming INI file entry [%(old_s)s] > %(old_o)s  to  [%(new_s)s] > %(new_o)s"
msgstr "INIファイルエントリの名前を変更 [%(old_s)s] > %(old_o)s  to [%(new_s)s] > %(new_o)s"

#: musicbot/config.py:2525
msgid "Upgrading config file with renamed options..."
msgstr "名前を変更したオプション付き設定ファイルをアップグレード中..."

#: musicbot/config.py:2542
msgid "Failed to upgrade config.  You'll need to upgrade it manually."
msgstr "設定のアップグレードに失敗しました。手動でアップグレードする必要があります。"

#: musicbot/config.py:2583
#, python-format
msgid "Block list file not found:  %s"
msgstr "ブロックリストファイルが見つかりません:  %s"

#: musicbot/config.py:2604
#, python-format
msgid "Could not load block list from file:  %s"
msgstr "ファイルからブロックリストを読み込めませんでした:  %s"

#: musicbot/config.py:2642 musicbot/config.py:2675
#, python-format
msgid "Could not update the block list file:  %s"
msgstr "ブロックリストファイルを更新できませんでした:  %s"

#: musicbot/config.py:2702
#, python-format
msgid "Loaded User Block list with %s entries."
msgstr "%s エントリでユーザーブロックリストを読み込みました。"

#: musicbot/config.py:2713
#, python-format
msgid "We found a legacy blacklist file, it will be renamed to:  %s"
msgstr "レガシーブラックリストファイルを見つけました。名前は  %sに変更されます。"

#: musicbot/config.py:2759
#, python-format
msgid "Loaded a Song Block list with %s entries."
msgstr "%s エントリでソングブロックリストをロードしました。"

#: musicbot/constructs.py:221
msgid ""
"Cannot load data for guild with ID 0. This is likely a bug in the code!"
msgstr "ID0のギルドのデータをロードできません。コード内のバグでしょう！"

#: musicbot/constructs.py:230
#, python-format
msgid "No file for guild %(id)s/%(name)s"
msgstr "ギルド %(id)s/%(name)s のファイルがありません"

#: musicbot/constructs.py:239
#, python-format
msgid "Loading guild data for guild with ID:  %(id)s/%(name)s"
msgstr "IDを持つギルドのギルドデータをロードしています:  %(id)s/%(name)s"

#: musicbot/constructs.py:246
#, python-format
msgid "An OS error prevented reading guild data file:  %s"
msgstr "ギルドデータファイル  %s の読み込みに失敗しました。"

#: musicbot/constructs.py:257
#, python-format
msgid "Guild %(id)s/%(name)s has custom command prefix: %(prefix)s"
msgstr "Guild %(id)s/%(name)s にカスタムコマンドプレフィックスがあります: %(prefix)s"

#: musicbot/constructs.py:277
msgid ""
"Cannot save data for guild with ID 0. This is likely a bug in the code!"
msgstr "ID 0のギルドのデータを保存できません。コード内のバグです！"

#: musicbot/constructs.py:301
msgid "Could not save guild specific data due to OS Error."
msgstr "OS エラーのため、ギルド固有のデータを保存できませんでした。"

#: musicbot/constructs.py:304
msgid "Failed to serialize guild specific data due to invalid data."
msgstr "無効なデータのため、ギルド固有のデータをシリアライズできませんでした。"

#: musicbot/downloader.py:94
#, python-format
msgid "Forcing YTDLP to use User Agent:  %s"
msgstr "ユーザーエージェントの使用を強制する YTDLP :  %s"

#: musicbot/downloader.py:105
#, python-format
msgid "MusicBot will use cookies for yt-dlp from:  %s"
msgstr "MusicBotはyt-dlpにクッキーを使用します:  %s"

#: musicbot/downloader.py:111
msgid "Yt-dlp will use your configured proxy server."
msgstr "Yt-dlpは設定したプロキシサーバーを使用します。"

#: musicbot/downloader.py:134
msgid ""
"Original OAuth2 plugin is installed and will be used instead.\n"
"This may cause MusicBot to not close completely, or hang pending authorization!\n"
"To close MusicBot, you must manually Kill the MusicBot process!\n"
"Yt-dlp is being set to show warnings and other log messages, to show the Auth code.\n"
"Uninstall the yt-dlp-youtube-oauth2 package to use integrated OAuth2 features instead."
msgstr ""

#: musicbot/downloader.py:232
msgid "HEAD seems to have no headers..."
msgstr "ヘッダがないみたいだな。"

#: musicbot/downloader.py:243
msgid "Checking media headers failed due to timeout."
msgstr "タイムアウトのためメディアヘッダーの確認に失敗しました。"

#: musicbot/downloader.py:246
#, python-format
msgid "Failed HEAD request for:  %s"
msgstr "%sへのヘッド要求に失敗しました"

#: musicbot/downloader.py:247
msgid "HEAD Request exception: "
msgstr "HEAD リクエストの例外: "

#: musicbot/downloader.py:315
#, python-format
msgid ""
"Sanitized YTDL Extraction Info (not JSON):\n"
"%s"
msgstr ""
"サニタイズYTDL抽出情報（JSONではありません）：\n"
"%s"

#: musicbot/downloader.py:317
#, python-format
msgid "Sanitized YTDL Extraction Info (not JSON):  %s"
msgstr "サニタイズYTDL抽出情報 (JSONではありません):  %s"

#: musicbot/downloader.py:381
msgid "Song info extraction returned no data."
msgstr "曲情報の抽出はデータを返しませんでした。"

#: musicbot/downloader.py:437
#, python-format
msgid "Called extract_info with:  '%(subject)s', %(args)s, %(kws)s"
msgstr "extract_infoと呼ばれる: '%(subject)s', %(args)s, %(kws)s"

#: musicbot/downloader.py:445
msgid "Cannot run extraction, loop is closed. (This is normal on shutdowns.)"
msgstr "抽出を実行できません。ループは閉じられています。（シャットダウン時は正常です）"

#: musicbot/downloader.py:447
msgid "Cannot continue extraction, event loop is closed."
msgstr "抽出を続行できません。イベントループは閉じられています。"

#: musicbot/downloader.py:456
msgid "Spotify URL is invalid or not supported."
msgstr "SpotifyのURLが無効かサポートされていません。"

#: musicbot/downloader.py:489 musicbot/downloader.py:510
#, python-format
msgid "Error in yt-dlp while downloading data: %(raw_error)s"
msgstr "データのダウンロード中にyt-dlpでエラーが発生しました: %(raw_error)s"

#: musicbot/downloader.py:493
msgid "Download Error with stream URL"
msgstr "ストリームURLのダウンロードエラー"

#: musicbot/downloader.py:498
msgid "Assuming content is a direct stream"
msgstr "コンテンツがダイレクトストリームであると仮定する"

#: musicbot/downloader.py:506
msgid "Cannot stream an invalid URL."
msgstr "無効なURLをストリーミングできません。"

#: musicbot/downloader.py:517
msgid ""
"Caught NoSupportingHandlers, trying again after replacing colon with space."
msgstr "NoSupportingHandlersをキャッチし、コロンをスペースに置き換えた後に再試行します。"

#: musicbot/downloader.py:544
msgid ""
"Extractor youtube:search returned single-entry result, replacing base info "
"with entry info."
msgstr "Extractorのyoutube:searchはシングルエントリ結果を返し、基本情報をエントリ情報に置き換えます。"

#: musicbot/downloader.py:560
#, python-format
msgid "Called safe_extract_info with:  %(args)s, %(kws)s"
msgstr "safe_extract_infoと呼ばれています:  %(args)s, %(kws)s"

#: musicbot/downloader.py:580
msgid "The local media file could not be found."
msgstr "ローカルメディアファイルが見つかりません。"

#: musicbot/downloader.py:618
msgid "Missing __input_subject from YtdlpResponseDict"
msgstr "YtdlpResponseDictから__input_subjectがありません"

#: musicbot/downloader.py:623
msgid ""
"Entries is not a list in YtdlpResponseDict, set process=True to avoid this."
msgstr "エントリは YtdlpResponseDict のリストではありません。 process=True に設定してこれを回避します。"

#: musicbot/downloader.py:852
#, python-format
msgid "Warning, duration error for: %(url)s"
msgstr "警告、期間エラー： %(url)s"

#: musicbot/entry.py:45
msgid "module 'pymediainfo' not found, will fall back to ffprobe."
msgstr "'pymediainfo' モジュールが見つかりません。ffprobe に戻ります。"

#: musicbot/entry.py:135
#, python-format
msgid "Created future for %r"
msgstr "%r のために未来を作成しました"

#: musicbot/entry.py:147
#, python-format
msgid "Completed futures for %(entry)r with %(callback)r"
msgstr "%(entry)r の %(callback)r の先物を完成させました"

#: musicbot/entry.py:157
msgid "Unhandled exception in _for_each_future callback."
msgstr "_for_each_future コールバックで未処理の例外です。"

#: musicbot/entry.py:188
#, python-format
msgid "Starting asyncio subprocess (%(process)s) with command: %(run)s"
msgstr "asyncio サブプロセス (%(process)s) をコマンド: %(run)s で開始"

#: musicbot/entry.py:223
#, python-format
msgid ""
"Extraction did not provide a duration for this entry.\n"
"MusicBot cannot estimate queue times until it is downloaded.\n"
"Entry name:  %s"
msgstr ""
"抽出はこのエントリの期間を提供しませんでした。\n"
"MusicBotはダウンロードされるまでキューの時間を推定できません。\n"
"エントリ名:  %s"

#: musicbot/entry.py:339 musicbot/entry.py:850 musicbot/entry.py:1069
msgid "Entry data is missing version number, cannot deserialize."
msgstr "Entry data is missing version number, cannot deerialize."

#: musicbot/entry.py:342 musicbot/entry.py:853 musicbot/entry.py:1072
msgid "Entry data has the wrong version number, cannot deserialize."
msgstr "Entry data has the wrong version number, cannot deerialize."

#: musicbot/entry.py:358
#, python-format
msgid "Deserialized URLPlaylistEntry cannot find channel with ID:  %s"
msgstr "Deserialized URLPlaylistEntry cannot find channel with ID:  %s"

#: musicbot/entry.py:374
#, python-format
msgid "Deserialized URLPlaylistEntry has the wrong channel type:  %s"
msgstr "Deserialized URLPlaylistEntry has the wrong channel type:  %s"

#: musicbot/entry.py:396
#, python-format
msgid "Deserialized URLPlaylistEntry cannot find author with ID:  %s"
msgstr "Deserialized URLPlaylistEntry cannot find author with ID:  %s"

#: musicbot/entry.py:402
msgid ""
"Deserialized URLPlaylistEntry has an author ID but no channel for lookup!"
msgstr ""
"Deserialized URLPlaylistEntry has an author ID but no channel for lookup!"

#: musicbot/entry.py:412 musicbot/entry.py:919 musicbot/entry.py:1142
#, python-format
msgid "Could not load %s"
msgstr "%s を読み込めませんでした"

#: musicbot/entry.py:449
#, python-format
msgid "Cannot download Spotify links, processing error with type: %(type)s"
msgstr "Spotifyのリンクをダウンロードできません。 %(type)s"

#: musicbot/entry.py:461 musicbot/entry.py:924 musicbot/entry.py:1175
#, python-format
msgid "Getting ready for entry:  %r"
msgstr "エントリの準備をしています:  %r"

#: musicbot/entry.py:478
msgid "Download cached with different extension..."
msgstr "別の拡張機能でキャッシュをダウンロード..."

#: musicbot/entry.py:487
msgid "Local size different from remote size. Re-downloading..."
msgstr "ローカルサイズとリモートサイズが異なります。再ダウンロード中..."

#: musicbot/entry.py:491
#, python-format
msgid "Download already cached at:  %s"
msgstr "既にキャッシュされているダウンロード:  %s"

#: musicbot/entry.py:511 musicbot/entry.py:1191
#, python-format
msgid ""
"MusicBot could not get duration data for this entry.\n"
"Queue time estimation may be unavailable until this track is cleared.\n"
"Entry file: %s"
msgstr ""
"MusicBotはこのエントリの期間データを取得できませんでした。\n"
"このトラックがクリアされるまでキューの時間推定は利用できません。\n"
"エントリファイル: %s"

#: musicbot/entry.py:518
#, python-format
msgid "Got duration of %(time)s seconds for file:  %(file)s"
msgstr "ファイルの %(time)s 秒間の持続時間：  %(file)s"

#: musicbot/entry.py:529 musicbot/entry.py:1209
msgid ""
"There as a problem with working out EQ, likely caused by a strange "
"installation of FFmpeg. This has not impacted the ability for the bot to "
"work, but will mean your tracks will not be equalized."
msgstr ""
"おそらくFFmpegの奇妙な設置によって引き起こされるEQを解決するには問題があります。 "
"これはBotの機能に影響を与えていませんが、トラックがイコライズされないことを意味します。"

#: musicbot/entry.py:541 musicbot/entry.py:1222
msgid "Exception while checking entry data."
msgstr "エントリデータを確認中の例外"

#: musicbot/entry.py:552 musicbot/entry.py:1233
#, python-format
msgid "Trying to get duration via pymediainfo for:  %s"
msgstr "pymediainfo経由で継続時間を取得しようとしています:  %s"

#: musicbot/entry.py:558 musicbot/entry.py:1239
msgid "Failed to get duration via pymediainfo."
msgstr "pymediainfo経由で継続時間を取得できませんでした。"

#: musicbot/entry.py:565 musicbot/entry.py:1246
#, python-format
msgid "Trying to get duration via ffprobe for:  %s"
msgstr "ffprobe 経由で継続時間を取得しようとしています:  %s"

#: musicbot/entry.py:568 musicbot/entry.py:1249
msgid "Could not locate ffprobe in your path!"
msgstr "パス内の ffprobe が見つかりませんでした！"

#: musicbot/entry.py:589 musicbot/entry.py:1270
msgid "ffprobe returned something that could not be used."
msgstr "FFプローブは使えないものを返しました"

#: musicbot/entry.py:592 musicbot/entry.py:1273
msgid "ffprobe could not be executed for some reason."
msgstr "何らかの理由でFFプローブを実行できなかった"

#: musicbot/entry.py:602 musicbot/entry.py:1283
#, python-format
msgid "Calculating mean volume of:  %s"
msgstr "%s の平均音量を計算しています"

#: musicbot/entry.py:605 musicbot/entry.py:1286
msgid "Could not locate ffmpeg on your path!"
msgstr "パス上にffmpegが見つかりませんでした！"

#: musicbot/entry.py:631 musicbot/entry.py:1312
msgid "Could not parse 'I' in normalize json."
msgstr "jsonの正規化で「I」を解析できませんでした。"

#: musicbot/entry.py:639 musicbot/entry.py:1320
msgid "Could not parse 'LRA' in normalize json."
msgstr "jsonの正規化で「LRA」を解析できませんでした。"

#: musicbot/entry.py:647 musicbot/entry.py:1328
msgid "Could not parse 'TP' in normalize json."
msgstr "jsonの正規化で「TP」を解析できませんでした。"

#: musicbot/entry.py:655 musicbot/entry.py:1336
msgid "Could not parse 'thresh' in normalize json."
msgstr "json正規化で「しきい値」を解析できませんでした。"

#: musicbot/entry.py:663 musicbot/entry.py:1344
msgid "Could not parse 'offset' in normalize json."
msgstr "jsonの正規化で「オフセット」を解析できませんでした。"

#: musicbot/entry.py:680
#, python-format
msgid "Download started:  %r"
msgstr "ダウンロード開始:  %r"

#: musicbot/entry.py:685
#, python-format
msgid "Download attempt %s of 3..."
msgstr "ダウンロードの試み %s / 3..."

#: musicbot/entry.py:697
#, python-format
msgid ""
"Download incomplete, retrying in %(time).1f seconds.  Reason: %(raw_error)s"
msgstr "%(time).1f秒でダウンロードできません。理由: %(raw_error)s"

#: musicbot/entry.py:705
#, python-format
msgid "Download failed, not retrying! Reason:  %(raw_error)s"
msgstr "ダウンロードに失敗しました。再試行できませんでした！理由：  %(raw_error)s"

#: musicbot/entry.py:710
#, python-format
msgid "Download did not complete due to an error: %(raw_error)s"
msgstr "エラーが発生したため、ダウンロードが完了しませんでした: %(raw_error)s"

#: musicbot/entry.py:716
#, python-format
msgid "Download failed due to a yt-dlp error: %(raw_error)s"
msgstr "yt-dlpエラーのためダウンロードに失敗しました: %(raw_error)s"

#: musicbot/entry.py:722
msgid "Extraction encountered an unhandled exception."
msgstr "抽出で処理されていない例外が発生しました。"

#: musicbot/entry.py:726
#, python-format
msgid "Download failed due to an unhandled exception: %(raw_error)s"
msgstr "未処理の例外のためダウンロードに失敗しました: %(raw_error)s"

#: musicbot/entry.py:731
#, python-format
msgid "Download failed:  %r"
msgstr "ダウンロードに失敗しました:  %r"

#: musicbot/entry.py:732
msgid "Failed to extract data for the requested media."
msgstr "要求されたメディアのデータの抽出に失敗しました。"

#: musicbot/entry.py:734
#, python-format
msgid "Download complete:  %r"
msgstr "ダウンロードが完了しました:  %r"

#: musicbot/entry.py:866
#, python-format
msgid "Deserialized StreamPlaylistEntry cannot find channel with ID:  %s"
msgstr "Deserialized StreamPlaylistEntry cannot find channel with ID:  %s"

#: musicbot/entry.py:882
#, python-format
msgid "Deserialized StreamPlaylistEntry has the wrong channel type:  %s"
msgstr "Deserialized StreamPlaylistEntry has the wrong channel type:  %s"

#: musicbot/entry.py:904
#, python-format
msgid "Deserialized StreamPlaylistEntry cannot find author with ID:  %s"
msgstr "Deserialized StreamPlaylistEntry cannot find author with ID:  %s"

#: musicbot/entry.py:910
msgid ""
"Deserialized StreamPlaylistEntry has an author ID but no channel for lookup!"
msgstr "Deserialized StreamPlaylistEntry には作者IDがありますが、検索のためのチャンネルはありません!"

#: musicbot/entry.py:1088
#, python-format
msgid "Deserialized LocalFilePlaylistEntry cannot find channel with ID:  %s"
msgstr "Deserialized LocalFilePlaylistEntry cannot find channel with ID:  %s"

#: musicbot/entry.py:1104
#, python-format
msgid "Deserialized LocalFilePlaylistEntry has the wrong channel type:  %s"
msgstr "Deserialized LocalFilePlaylistEntry has the wrong channel type:  %s"

#: musicbot/entry.py:1126
#, python-format
msgid "Deserialized LocalFilePlaylistEntry cannot find author with ID:  %s"
msgstr "Deserialized LocalFilePlaylistEntry cannot find author with ID:  %s"

#: musicbot/entry.py:1132
msgid ""
"Deserialized LocalFilePlaylistEntry has an author ID but no channel for "
"lookup!"
msgstr ""
"Deserialized LocalFilePlaylistEntry にはauthor IDがありますが、検索のためのチャンネルはありません!"

#: musicbot/entry.py:1198
#, python-format
msgid "Got duration of %(seconds)s seconds for file:  %(file)s"
msgstr "ファイルの %(seconds)s 秒間の持続時間：  %(file)s"

#: musicbot/filecache.py:120
#, python-format
msgid "Failed to delete cache file:  %s"
msgstr "キャッシュファイルの削除に失敗しました:  %s"

#: musicbot/filecache.py:131
msgid "Audio cache directory has been removed."
msgstr "オーディオキャッシュディレクトリが削除されました。"

#: musicbot/filecache.py:138
msgid "Audio cache directory could not be removed or renamed."
msgstr "オーディオキャッシュディレクトリを削除または名前を変更できませんでした。"

#: musicbot/filecache.py:145
msgid "Audio cache directory could not be removed."
msgstr "オーディオキャッシュディレクトリを削除できませんでした。"

#: musicbot/filecache.py:154
msgid "Audio cache has no limits set, nothing to delete."
msgstr "オーディオキャッシュに制限が設定されていません。削除するものはありません。"

#: musicbot/filecache.py:217
#, python-format
msgid "Audio cache deleted %(number)s file(s), total of %(size)s removed."
msgstr "オーディオキャッシュは %(number)s ファイルを削除しました。 %(size)s の合計が削除されました。"

#: musicbot/filecache.py:225
#, python-format
msgid ""
"Audio cached retained %(number)s file(s) from autoplaylist, total of "
"%(size)s retained."
msgstr "自動プレイリストからのオーディオキャッシュ保持 %(number)s ファイル、 %(size)s の合計。"

#: musicbot/filecache.py:234
#, python-format
msgid "Audio cache is now %(size)s over %(number)s file(s)."
msgstr "オーディオキャッシュは %(size)s ファイルよりも %(number)s になりました。"

#: musicbot/filecache.py:250
msgid "Audio cache directory is missing, nothing to delete."
msgstr "オーディオキャッシュディレクトリがありません。削除するものはありません。"

#: musicbot/filecache.py:269
msgid ""
"Audio cache file is from autoplaylist but marked as busted, ignoring it."
msgstr "オーディオキャッシュファイルは自動プレイリストからですが、破損した場合は無視してマークされています。"

#: musicbot/filecache.py:280
#, python-format
msgid "Cache level requires cleanup. %s"
msgstr "キャッシュレベルをクリアする必要があります。 %s"

#: musicbot/filecache.py:304
msgid "Auto playlist has no cache map, moving on."
msgstr "自動プレイリストにキャッシュマップがありません。移動中です。"

#: musicbot/filecache.py:312
#, python-format
msgid "Loaded auto playlist cache map with %s entries."
msgstr "%s エントリで自動プレイリストキャッシュマップをロードしました。"

#: musicbot/filecache.py:316
msgid "Failed to load auto playlist cache map."
msgstr "自動プレイリストキャッシュマップの読み込みに失敗しました。"

#: musicbot/filecache.py:341
#, python-format
msgid "Saved auto playlist cache map with %s entries."
msgstr "%s のエントリで自動プレイリストキャッシュマップを保存しました。"

#: musicbot/filecache.py:345
msgid "Failed to save auto playlist cache map."
msgstr "自動プレイリストキャッシュマップの保存に失敗しました。"

#: musicbot/filecache.py:363
#, python-format
msgid ""
"Auto playlist cache map conflict on Key: %(file)s  Old: %(old)s  New: "
"%(new)s"
msgstr "キー: %(file)s  古い: %(old)s  新着: %(new)s"

#: musicbot/i18n.py:229
#, python-format
msgid "Lang Argument Error:  %s"
msgstr "ラング引数エラー:  %s"

#: musicbot/i18n.py:290
#, python-format
msgid "Failed to load log translations for any of:  [%s]  in:  %s"
msgstr "[%s]  のいずれかのログ翻訳の読み込みに失敗しました:  %s"

#: musicbot/i18n.py:338
#, python-format
msgid ""
"Failed to load discord translations for any of:  [%s]  guild:  %s  in:  %s"
msgstr "いずれかの不和翻訳の読み込みに失敗しました:  [%s]  ギルド:  %s  in:  %s"

#: musicbot/json.py:14
#, python-format
msgid "Loading JSON file: %s"
msgstr "JSON ファイルの読み込み中: %s"

#: musicbot/json.py:27
#, python-format
msgid "Error parsing %s as JSON"
msgstr "%s を JSON として解析中にエラーが発生しました"

#: musicbot/json.py:36
#, python-format
msgid "Could not grab data from JSON key: %s"
msgstr "JSON キーからデータを取得できませんでした: %s"

#: musicbot/logs.py:131
msgid "Skipping logger setup, already set up"
msgstr "ロガーの設定をスキップしています。既に設定されています"

#: musicbot/logs.py:283
#, python-format
msgid "Log level was previously set via override to: %s"
msgstr "ログレベルは、オーバーライドを介して %sに設定されています"

#: musicbot/logs.py:292
#, python-format
msgid "Changing log level to:  %s"
msgstr "ログレベルを  %sに変更しました"

#: musicbot/logs.py:321
msgid "MusicBot loggers have been called to shut down."
msgstr "MusicBotロガーがシャットダウンするように呼び出されました。"

#: musicbot/permissions.py:120
#, python-format
msgid "Permissions file not found, copying from:  %s"
msgstr "パーミッションファイルが見つかりません。コピー元：  %s"

#: musicbot/permissions.py:129
#, python-format
msgid "Error copying example permissions file:  %s"
msgstr "例のパーミッションファイルのコピーエラー:  %s"

#: musicbot/permissions.py:195
msgid "Config 'OwnerID' is set auto, will set correctly later."
msgstr "設定 'OwnerID' が auto に設定されており、後で正しく設定されます。"

#: musicbot/permissions.py:212
msgid "Validating permissions..."
msgstr "権限を検証しています..."

#: musicbot/permissions.py:214
msgid "Setting auto 'OwnerID' for owner permissions group."
msgstr "オーナー権限グループに自動的に 'OwnerID' を設定します。"

#: musicbot/permissions.py:268
#, python-format
msgid "Updating group in permissions file:  %s"
msgstr "権限ファイルのグループを更新中:  %s"

#: musicbot/permissions.py:274
#, python-format
msgid "Deleting group from permissions file:  %s"
msgstr "権限ファイルからグループを削除しています:  %s"

#: musicbot/permissions.py:279
#, python-format
msgid "Adding new group to permissions file:  %s"
msgstr "権限ファイルに新しいグループを追加:  %s"

#: musicbot/permissions.py:294
msgid "Saving permissions file now."
msgstr "権限ファイルを保存中です。"

#: musicbot/permissions.py:300
msgid "ConfigUpdater could not parse the permissions file!"
msgstr "ConfigUpdater が権限ファイルを解析できませんでした！"

#: musicbot/permissions.py:302
msgid "You have a duplicate section, fix your Permissions file!"
msgstr "重複したセクションがあります。権限ファイルを修正してください！"

#: musicbot/permissions.py:304
#, python-format
msgid "Failed to save permissions group:  %s"
msgstr "権限グループの保存に失敗しました:  %s"

#: musicbot/permissions.py:319
msgid "Dev Bug! Permission has getter that is not available."
msgstr "Dev Bug! 権限には利用できない権限があります。"

#: musicbot/permissions.py:324
msgid ""
"Dev Bug! Permission has invalid type, getter and default must be the same "
"type."
msgstr "開発バグ！権限が無効な型、getterとデフォルトは同じ型でなければなりません。"

#: musicbot/permissions.py:565
msgid "Max search items can't be larger than 100. Setting to 100."
msgstr "最大検索項目は100より大きくすることはできません。100に設定してください。"

#: musicbot/permissions.py:643
#, python-format
msgid ""
"You do not have permission to play the requested media.\n"
"The yt-dlp extractor `%(extractor)s` is not permitted in your group."
msgstr ""
"リクエストされたメディアを再生する権限がありません。\n"
"yt-dlp extractor `%(extractor)s` はあなたのグループでは許可されていません。"

#: musicbot/player.py:85
#, python-format
msgid "Cleanup got called on the audio source:  %r"
msgstr "クリーンアップがオーディオソースに呼び出されました:  %r"

#: musicbot/player.py:190
#, python-format
msgid "MusicPlayer.skip() is called:  %s"
msgstr "MusicPlayer.skip() が呼び出されました:  %s"

#: musicbot/player.py:200
#, python-format
msgid "MusicPlayer.stop() is called:  %s"
msgstr "MusicPlayer.stop() が呼び出されました:  %s"

#: musicbot/player.py:215
msgid "Guild or network unavailable, cannot resume playback."
msgstr "ギルドまたはネットワークが利用できません。再生を再開できません。"

#: musicbot/player.py:219
#, python-format
msgid "MusicPlayer.resume() is called:  %s"
msgstr "MusicPlayer.resume() が呼び出されました:  %s"

#: musicbot/player.py:239
#, python-format
msgid "MusicPlayer.pause() is called:  %s"
msgstr "MusicPlayer.pause() が呼び出されました:  %s"

#: musicbot/player.py:261
#, python-format
msgid "MusicPlayer.kill() is called:  %s"
msgstr "MusicPlayer.kill() が呼び出されました:  %s"

#: musicbot/player.py:287
msgid "Playback finished, but _current_entry is None."
msgstr "再生は終了しましたが、_current_entry は None です。"

#: musicbot/player.py:342
msgid "Possible Warning from kill_current_player()"
msgstr "kill_current_player() から可能な警告"

#: musicbot/player.py:361
#, python-format
msgid "MusicPlayer.play() is called:  %s"
msgstr "MusicPlayer.play() が呼び出されました:  %s"

#: musicbot/player.py:371
msgid "MusicPlayer is dead, cannot play."
msgstr "MusicPlayerが動作しません。再生できません。"

#: musicbot/player.py:376
msgid "Guild or network unavailable, cannot start playback."
msgstr "ギルドまたはネットワークが利用できません。再生を開始できません。"

#: musicbot/player.py:381
msgid "MusicPlayer was previously paused, resuming current player."
msgstr "MusicPlayerは以前に一時停止していました。現在のプレーヤーを再開しています。"

#: musicbot/player.py:387
msgid "MusicPlayer already locked for playback, this call is ignored."
msgstr "MusicPlayerはすでに再生のためにロックされています。この呼び出しは無視されます。"

#: musicbot/player.py:398
msgid "Failed to get next entry."
msgstr "次のエントリを取得できませんでした。"

#: musicbot/player.py:402
msgid "Failed to process entry for playback."
msgstr "再生のためのエントリを処理できませんでした。"

#: musicbot/player.py:453
#, python-format
msgid "Creating player with options: ffmpeg %(before)s -i %(input)s %(after)s"
msgstr "オプションでプレイヤーを作成: ffmpeg %(before)s -i %(input)s %(after)s"

#: musicbot/player.py:457
#, python-format
msgid "Playing %(source)r using %(client)r"
msgstr "%(source)r で %(client)r を再生中"

#: musicbot/player.py:488
#, python-format
msgid "Skipping deletion of '%s', found song in queue"
msgstr "'%s'の削除をスキップして、キューに曲を見つけました"

#: musicbot/player.py:492
#, python-format
msgid "Deleting file:  %s"
msgstr "ファイルを削除しています:  %s"

#: musicbot/player.py:497
#, python-format
msgid "File deleted:  %s"
msgstr "ファイルを削除しました:  %s"

#: musicbot/player.py:501
msgid "Cannot delete file, it is currently in use."
msgstr "ファイルを削除できません。現在使用中です。"

#: musicbot/player.py:504
msgid "Cannot delete file due to a permission error."
msgstr "パーミッションエラーのためファイルを削除できません。"

#: musicbot/player.py:509
msgid "Cannot delete file, it was not found."
msgstr "ファイルを削除できません。見つかりませんでした。"

#: musicbot/player.py:515
msgid "Error while trying to delete file."
msgstr "ファイルの削除中にエラーが発生しました。"

#: musicbot/player.py:520
msgid "Could not delete file, giving up and moving on"
msgstr "ファイルを削除できませんでした。あきらめて次に進みます"

#: musicbot/player.py:581
#, python-format
msgid "Deserialize returned an object that is not a MusicPlayer:  %s"
msgstr "MusicPlayerではないオブジェクトをデシリアライズして返されました:  %s"

#: musicbot/player.py:586
msgid "Failed to deserialize player"
msgstr "プレイヤーのデシリアライズに失敗しました"

#: musicbot/player.py:648
#, python-format
msgid "Data from ffmpeg: %s"
msgstr "ffmpegからのデータ: %s"

#: musicbot/player.py:658
#, python-format
msgid "Error from ffmpeg: %s"
msgstr "ffmpegからのエラー: %s"

#: musicbot/player.py:666
#, python-format
msgid "Warning from ffmpeg:  %s"
msgstr "ffmpegからの警告:  %s"

#: musicbot/player.py:695
msgid "Unknown error decoding message from ffmpeg"
msgstr "ffmpegからの不明なエラーデコードメッセージ"

#: musicbot/player.py:699
#, python-format
msgid "Decoded data from ffmpeg: %s"
msgstr "ffmpegからデータをデコードしました: %s"

#: musicbot/playlist.py:121
#, python-format
msgid "Adding stream entry for URL:  %(url)s"
msgstr "URLのストリームエントリを追加しています:  %(url)s"

#: musicbot/playlist.py:159
msgid "Could not extract information"
msgstr "情報を抽出できませんでした"

#: musicbot/playlist.py:163
msgid "This is a playlist."
msgstr "これはプレイリストです。"

#: musicbot/playlist.py:177
msgid "Entry info appears to be a stream, adding stream entry..."
msgstr "Entry info appears to be a stream, adding stream entry..."

#: musicbot/playlist.py:195
#, python-format
msgid "Invalid content type `%(type)s` for URL: %(url)s"
msgstr "無効なコンテンツタイプ`%(type)s`の URL: %(url)s"

#: musicbot/playlist.py:203
msgid "Got text/html for content-type, this might be a stream."
msgstr "content-typeについては text/html を取得しました。これはストリームかもしれません。"

#: musicbot/playlist.py:210
#, python-format
msgid "Questionable content-type \"%(type)s\" for url:  %(url)s"
msgstr "疑問のあるコンテンツタイプ \"%(type)s\" for url:  %(url)s"

#: musicbot/playlist.py:215
#, python-format
msgid "Adding URLPlaylistEntry for: %(subject)s"
msgstr "%(subject)s の URLPlaylistEntry を追加中"

#: musicbot/playlist.py:235
#, python-format
msgid "Adding LocalFilePlaylistEntry for: %(subject)s"
msgstr "LocalFilePlaylistEntry の追加: %(subject)s"

#: musicbot/playlist.py:280
#, python-format
msgid "Ignored video from compound playlist link with ID:  %s"
msgstr "ID：  %s との複合プレイリストリンクから無視されたビデオ"

#: musicbot/playlist.py:292
#, python-format
msgid ""
"Not allowing entry that is in song block list:  %(title)s  URL: %(url)s"
msgstr "曲のブロックリストにあるエントリが許可されていません:  %(title)s  URL: %(url)s"

#: musicbot/playlist.py:305
#, python-format
msgid ""
"Ignoring song in entries by '%s', duration longer than permitted maximum."
msgstr "「%s」のエントリ内の曲を無視しています。許可されている最大より長くなっています。"

#: musicbot/playlist.py:317
#, python-format
msgid "Not adding YouTube video because it is marked private or deleted:  %s"
msgstr "プライベートまたは削除のマークがあるため、YouTube 動画を追加しません:  %s"

#: musicbot/playlist.py:342
msgid "Could not add item"
msgstr "アイテムを追加できませんでした"

#: musicbot/playlist.py:343
#, python-format
msgid "Item: %s"
msgstr "アイテム: %s"

#: musicbot/playlist.py:346
#, python-format
msgid "Skipped %s bad entries"
msgstr "%s 不良項目をスキップしました"

#: musicbot/playlist.py:387
msgid "Reorder looping over entries."
msgstr "エントリのループを順序変更します。"

#: musicbot/playlist.py:469
#, python-format
msgid "Pre-downloading next track:  %r"
msgstr "次のトラックを事前ダウンロード:  %r"

#: musicbot/playlist.py:495
msgid "no duration data"
msgstr "持続時間データがありません"

#: musicbot/playlist.py:504
msgid "no duration data in current entry"
msgstr "現在のエントリに期間データがありません"

#: musicbot/spotify.py:119
#, python-format
msgid "Invalid track_data, must be of type `track` got `%(type)s`"
msgstr "track_dataが無効です。%(type)s `が得られた`track`型でなければなりません。"

#: musicbot/spotify.py:301
#, python-format
msgid "Ignored non-track entry in playlist with type:  %s"
msgstr "%s のプレイリストでトラック以外のエントリが無視されました"

#: musicbot/spotify.py:487
#, python-format
msgid "Spotify Album total tacks:  %(total)s  Next URL: %(url)s"
msgstr "Spotifyのアルバムの合計タック数：  %(total)s  次のURL： %(url)s"

#: musicbot/spotify.py:492
#, python-format
msgid "Getting Spotify Album Next URL:  %s"
msgstr "Spotifyアルバムの次のURLを取得:  %s"

#: musicbot/spotify.py:503
#, python-format
msgid ""
"Spotify Album Object may not be complete, expected %(total)s tracks but got "
"%(number)s"
msgstr ""
"Spotifyのアルバムオブジェクトが完了しない場合があります。 %(total)s トラックが期待されますが、 %(number)sが取得されました"

#: musicbot/spotify.py:507
msgid "Spotify Album has more tracks than initial total."
msgstr "Spotifyのアルバムは最初の合計より多くのトラックを持っています。"

#: musicbot/spotify.py:530
#, python-format
msgid "Spotify Playlist total tacks: %(total)s  Next URL: %(url)s"
msgstr "Spotifyプレイリストの合計タック数： %(total)s  次のURL： %(url)s"

#: musicbot/spotify.py:535
#, python-format
msgid "Getting Spotify Playlist Next URL:  %s"
msgstr "Spotifyプレイリストを取得する 次のURL:  %s"

#: musicbot/spotify.py:546
#, python-format
msgid ""
"Spotify Playlist Object may not be complete, expected %(total)s tracks but "
"got %(number)s"
msgstr ""
"Spotifyプレイリストオブジェクトが完了しない場合があります。 %(total)s トラックを想定していますが、 %(number)sを獲得しました"

#: musicbot/spotify.py:550
msgid "Spotify Playlist has more tracks than initial total."
msgstr "Spotifyのプレイリストは、最初の合計よりも多くのトラックを持っています。"

#: musicbot/spotify.py:555
#, python-format
msgid "Spotify Playlist contained %s usable tracks."
msgstr "Spotifyプレイリストには、 %s 使用可能なトラックが含まれていました。"

#: musicbot/spotify.py:581 musicbot/spotify.py:617
#, python-format
msgid "Response status is not OK: [%(status)s] %(reason)s"
msgstr "応答ステータスが正しくありません: [%(status)s] %(reason)s"

#: musicbot/spotify.py:587 musicbot/spotify.py:623 musicbot/spotify.py:733
msgid "Response JSON did not decode to a dict!"
msgstr "Response JSON decode to a dict!"

#: musicbot/spotify.py:596
#, python-format
msgid "Failed making GET request to url:  %s"
msgstr "URLへのGETリクエストの作成に失敗しました:  %s"

#: musicbot/spotify.py:602
#, python-format
msgid "Could not make GET to URL:  %(url)s  Reason:  %(raw_error)s"
msgstr "URLにGETできませんでした:  %(url)s  理由:  %(raw_error)s"

#: musicbot/spotify.py:632
#, python-format
msgid "Failed making POST request to url:  %s"
msgstr "URLへのPOSTリクエストの作成に失敗しました:  %s"

#: musicbot/spotify.py:638
#, python-format
msgid "Could not make POST to URL:  %(url)s  Reason:  %(raw_error)s"
msgstr "URLへのPOSTを作成できませんでした:  %(url)s  理由:  %(raw_error)s"

#: musicbot/spotify.py:672
msgid ""
"Failed to get a guest token from Spotify, please try specifying client ID "
"and client secret"
msgstr "Spotifyからゲスト トークンを取得できませんでした。クライアント IDとクライアント シークレットを指定してみてください"

#: musicbot/spotify.py:679
msgid "Created a new Guest Mode access token."
msgstr "新しいゲストモードのアクセストークンを作成しました。"

#: musicbot/spotify.py:683
#, python-format
msgid ""
"API response did not contain the expected data. Missing key: %(raw_error)s"
msgstr "API応答に期待されるデータが含まれていませんでした。欠落キー: %(raw_error)s"

#: musicbot/spotify.py:689
#, python-format
msgid ""
"API response contained unexpected data.\n"
"%(raw_error)s"
msgstr ""
"API応答に予期しないデータが含まれていました。\n"
"%(raw_error)s"

#: musicbot/spotify.py:696
msgid "Requested a token from Spotify, did not end up getting one"
msgstr "Spotifyからトークンをリクエストしました。トークンを取得できませんでした"

#: musicbot/spotify.py:700
msgid "Created a new Client Mode access token."
msgstr "新しいクライアントモードアクセストークンを作成しました。"

#: musicbot/spotify.py:727
#, python-format
msgid "API response status is not OK: [%(status)s]  %(reason)s"
msgstr "API レスポンスの状態が正しくありません: [%(status)s]  %(reason)s"

#: musicbot/spotify.py:743
msgid "Failed to get Spotify Guest Token."
msgstr "Spotifyゲストトークンの取得に失敗しました。"

#: musicbot/spotify.py:750
#, python-format
msgid "Failed to get Guest Token due to: %(raw_error)s"
msgstr "ゲストトークンの取得に失敗しました: %(raw_error)s"

#: musicbot/utils.py:174
msgid "Only the owner can use this command."
msgstr "このコマンドを使用できるのはオーナーのみです。"

#: musicbot/utils.py:194
msgid "Only dev users can use this command."
msgstr "このコマンドは開発者のみが使用できます。"

#: musicbot/utils.py:280 musicbot/utils.py:322
msgid "Cannot count members when voice_channel is None."
msgstr "voice_channel が None の場合はメンバーをカウントできません。"

#: musicbot/ytdlp_oauth2_plugin.py:85
#, python-format
msgid "Failed to save ytdlp oauth2 token data due to:  %s"
msgstr "Ytdlp oauth2トークンデータの保存に失敗しました:  %s"

#: musicbot/ytdlp_oauth2_plugin.py:92
msgid "Loading YouTube TV OAuth2 token data."
msgstr "YouTube TV OAuth2トークンデータを読み込んでいます。"

#: musicbot/ytdlp_oauth2_plugin.py:102
#, python-format
msgid "Failed to load ytdlp oauth2 token data due to:  %s"
msgstr "Ytdlp oauth2トークンデータの読み込みに失敗しました:  %s"

#: musicbot/ytdlp_oauth2_plugin.py:110
msgid "Storing YouTube TV OAuth2 token data"
msgstr "YouTube TV OAuth2トークンデータの保存"

#: musicbot/ytdlp_oauth2_plugin.py:140
msgid "Invalid cached OAuth2 token data."
msgstr "不正なOAuth2トークンデータです。"

#: musicbot/ytdlp_oauth2_plugin.py:155
msgid "Access token expired, refreshing"
msgstr "アクセストークンの有効期限が切れました。更新しています"

#: musicbot/ytdlp_oauth2_plugin.py:176
msgid ""
"YouTube cookies have been provided, but OAuth2 is being used. If you "
"encounter problems, stop providing YouTube cookies to yt-dlp."
msgstr ""
"YouTubeクッキーが提供されていますが、OAuth2が使用されています。問題が発生した場合は、yt-"
"dlpにYouTubeクッキーを提供するのをやめてください。"

#: musicbot/ytdlp_oauth2_plugin.py:194
msgid "Refreshing YouTube TV oauth2 token..."
msgstr "YouTube TV oauth2トークンを更新中..."

#: musicbot/ytdlp_oauth2_plugin.py:212
#, python-format
msgid ""
"Failed to refresh OAuth2 access token due to:  %s\n"
"Restarting authorization flow..."
msgstr ""
"%s\n"
"認証フローを再起動中..."

#: musicbot/ytdlp_oauth2_plugin.py:230
msgid "Starting oauth2 flow..."
msgstr "oauth2 フローを開始しています..."

#: musicbot/ytdlp_oauth2_plugin.py:249
#, python-format
msgid ""
"\n"
"NOTICE:\n"
"To give yt-dlp access to your account, visit:\n"
"  %s\n"
"Then enter this authorization code:  %s\n"
"You have %s seconds to complete authorization.\n"
msgstr ""

#: musicbot/ytdlp_oauth2_plugin.py:258
msgid ""
"The application may hang until authorization time out if closed at this "
"point. This is normal."
msgstr "この時点で閉じた場合、アプリケーションは承認の時間が切れるまでハングアップすることができます。これは正常です。"

#: musicbot/ytdlp_oauth2_plugin.py:264
msgid "Timed out while waiting for OAuth2 token."
msgstr "OAuth2トークンの待機中にタイムアウトしました。"

#: musicbot/ytdlp_oauth2_plugin.py:292
msgid "The device code has expired, restarting authorization flow for yt-dlp."
msgstr "デバイス コードの有効期限が切れています。yt-dlp の認証フローを再起動します。"

#: musicbot/ytdlp_oauth2_plugin.py:298
msgid "Yt-dlp OAuth2 authorization successful."
msgstr "Yt-dlp OAuth2の承認に成功しました。"

#: musicbot/ytdlp_oauth2_plugin.py:328
#, python-format
msgid "Adding OAuth2 Plugin to Yt-dlp IE:  %s"
msgstr "Yt-dlp IEにOAuth2プラグインを追加:  %s"

#: musicbot/ytdlp_oauth2_plugin.py:350
#, python-format
msgid "Default Yt-dlp Clients:  %s"
msgstr "デフォルトの Yt-dlp クライアント:  %s"

#: run.py:105
msgid "Could not find git executable."
msgstr "git 実行可能ファイルが見つかりませんでした。"

#: run.py:154
msgid "Attempting to upgrade with `git pull` on current path."
msgstr "`git pull` を現在のパスにアップグレードしようとしています。"

#: run.py:161
#, python-format
msgid "Result of git pull:  %s"
msgstr "git pullの結果:  %s"

#: run.py:169
msgid "Upgrade failed, you need to run `git pull` manually."
msgstr "アップグレードに失敗しました。手動で`git pull`を実行する必要があります。"

#: run.py:179
msgid "Cannot execute pip."
msgstr "pipを実行できません。"

#: run.py:186
msgid "Error using -m method"
msgstr "-m メソッドの使用エラー"

#: run.py:232
msgid "PIP failed while calling sub-process."
msgstr "サブプロセスの呼び出し中にPIPが失敗しました。"

#: run.py:235
msgid "PIP failed due to Permission Error."
msgstr "パーミッションエラーのため、PIP が失敗しました。"

#: run.py:239
#, python-format
msgid "PIP failed due to missing Python executable?  (%s)"
msgstr "Python実行中にPIPが失敗しましたか? (%s)"

#: run.py:244
msgid "PIP failed due to OSError."
msgstr "OSError のため、PIP が失敗しました。"

#: run.py:265
msgid "Could not decode pip update report JSON."
msgstr "PIP更新レポートJSONをデコードできませんでした。"

#: run.py:287
msgid "Cannot locate or execute python -m pip"
msgstr "Pythonが見つからないか、実行できません -m pip"

#: run.py:290
#, python-format
msgid "Attempting to upgrade with `%s` on current path..."
msgstr "現在のパスで`%s`でアップグレードしようとしています..."

#: run.py:308
#, python-format
msgid ""
"Result of pip upgrade:\n"
"%s"
msgstr ""
"Pip アップグレードの結果:\n"
"%s"

#: run.py:313
#, python-format
msgid "Result exit code from pip upgrade: %s"
msgstr "pip アップグレードの結果終了コード: %s"

#: run.py:328
msgid "Upgrade failed to execute or we could not understand the output"
msgstr "アップグレードの実行に失敗したか、出力を理解できませんでした"

#: run.py:331
#, python-format
msgid "You may need to run `%s` manually."
msgstr "`%s`を手動で実行する必要があります。"

#: run.py:340
msgid "Press enter to continue . . ."
msgstr "続行するにはEnterキーを押します. . . . . . ."

#: run.py:353
msgid "Starting sanity checks"
msgstr "健全性チェックを開始中"

#: run.py:364
msgid "Required checks passed."
msgstr "必要なチェックが完了しました。"

#: run.py:377
msgid "Skipped checking for updates."
msgstr "更新の確認をスキップしました。"

#: run.py:379
msgid "Optional checks passed."
msgstr "オプションのチェックが完了しました。"

#: run.py:387
msgid "Checking for Python 3.8+"
msgstr "Python 3.8以上を確認しています"

#: run.py:391
#, python-format
msgid "Python 3.8+ is required. This version is %s"
msgstr "Python 3.8+ が必要です。このバージョンは %s です。"

#: run.py:393
msgid "Attempting to locate Python 3.8..."
msgstr "Python 3.8 を見つけようとしています..."

#: run.py:401
msgid "Could not locate py.exe"
msgstr "py.exe が見つかりませんでした"

#: run.py:412
msgid "Could not execute `py.exe -3.8` "
msgstr "`py.exe -3.8` を実行できませんでした "

#: run.py:416
msgid "Python 3 found.  Launching bot..."
msgstr "Python 3 が見つかりました。botを起動中..."

#: run.py:421
msgid "Trying \"python3.8\""
msgstr "\"python3.8\"を試しています"

#: run.py:424
msgid "Could not locate python3.8 on path."
msgstr "パス上で python3.8 が見つかりませんでした。"

#: run.py:438
#, python-format
msgid ""
"\n"
"Python 3.8 found.  Re-launching bot using: %s run.py\n"
msgstr ""
"\n"
"Python 3.8 が見つかりました。ボットの再起動: %s run.py\n"

#: run.py:443
msgid ""
"Could not find Python 3.8 or higher.  Please run the bot using Python 3.8"
msgstr "Python 3.8 以上を見つけることができませんでした。Python 3.8 を使用してボットを実行してください"

#: run.py:476
msgid "Ensuring we're in the right environment"
msgstr "適切な環境であることを確認する"

#: run.py:499
#, python-format
msgid "Failed environment check, %s"
msgstr "失敗した環境チェック、 %s"

#: run.py:540
#, python-format
msgid "Detected FFmpeg is installed at:  %s"
msgstr "検出されたFFmpegがインストールされています:  %s"

#: run.py:542
msgid "Adding local bins/ folder environment PATH for bundled ffmpeg..."
msgstr "ffmpegにローカルのbins/フォルダ環境PATHを追加する"

#: run.py:551
msgid ""
"MusicBot could not locate FFmpeg binary in your environment.\n"
"Please install FFmpeg so it is available in your environment PATH variable."
msgstr ""
"MusicBotがあなたの環境でFFmpegバイナリを見つけることができませんでした。\n"
"PATH変数で利用できるようにFFmpegをインストールしてください。"

#: run.py:556
msgid ""
"On Windows, you can add a pre-compiled EXE to the MusicBot `bin` folder,\n"
"or you can install FFmpeg system-wide using WinGet or by running the install.bat file."
msgstr ""
"Windowsでは、コンパイル済みEXEをMusicBot `bin`フォルダに追加できます。\n"
"またはWinGetを使用してFFmpegシステム全体をインストールするか、またはインストールを実行することができます。 ファイルに"

#: run.py:561
msgid ""
"On MacOS, you may be able to install FFmpeg via homebrew.\n"
"Otherwise, check the official FFmpeg site for build or install steps."
msgstr ""
"MacOSでは、Homebrew経由でFFmpegをインストールすることができます。\n"
"そうでなければ、公式FFmpegサイトでビルドまたはインストール手順を確認してください。"

#: run.py:566
msgid ""
"On Linux, many distros make FFmpeg available via system package managers.\n"
"Check for ffmpeg with your system package manager or build from sources."
msgstr ""
"Linuxの場合、多くのdistrosはシステムパッケージマネージャを介してFFmpegを利用可能にします。\n"
"システムパッケージマネージャでffmpegを確認するか、ソースからビルドします。"

#: run.py:579
#, python-format
msgid "Less than %sMB of free space remains on this device"
msgstr "%sMB 未満の空き容量がこのデバイスに残っています"

#: run.py:588
msgid ""
"\n"
"Checking for updates to MusicBot or dependencies..."
msgstr ""
"\n"
"MusicBotのアップデートや依存関係の確認..."

#: run.py:605
msgid "No MusicBot updates available via `git` command."
msgstr "`git`コマンドで利用可能なMusicBotのアップデートはありません。"

#: run.py:608
msgid ""
"Could not check for updates using `git` commands.  You should check "
"manually."
msgstr "`git` コマンドを使用してアップデートを確認できませんでした。手動で確認する必要があります。"

#: run.py:615
msgid "The following packages can be updated:\n"
msgstr "以下のパッケージを更新できます:\n"

#: run.py:621
#, python-format
msgid "  %s  to version:  %s\n"
msgstr "  %s  からバージョン:  %s\n"

#: run.py:632
msgid "No dependency updates available via `pip` command."
msgstr "`pip`コマンドで利用可能な依存関係の更新はありません。"

#: run.py:635
msgid ""
"Could not check for updates using `pip` commands.  You should check "
"manually."
msgstr "`pip`コマンドを使用してアップデートを確認できませんでした。手動で確認する必要があります。"

#: run.py:639
#, python-format
msgid ""
"You can run a guided update by using the command:\n"
"    %s ./update.py"
msgstr ""
"\n"
"    %s ./update.py コマンドを使用してガイド付き更新を実行できます。"

#: run.py:657
msgid "Value is above the maximum limit."
msgstr "値は最大限を超えています。"

#: run.py:659
msgid "Value must not be negative."
msgstr "値は負であってはなりません。"

#: run.py:663
#, python-format
msgid "Value for Max Logs Kept must be a number from 0 to %s"
msgstr "保持される最大ログの値は0から %sまでの数値でなければなりません"

#: run.py:673
#, python-format
msgid "Log level '%s' is not available."
msgstr "ログレベル「%s」は利用できません。"

#: run.py:677
#, python-format
msgid "Log Level must be one of:  %s"
msgstr "ログレベルは次のいずれかでなければなりません：  %s"

#: run.py:687
msgid ""
"Launch a music playing discord bot built using discord.py, youtubeDL, and "
"ffmpeg."
msgstr "discord.py、youtubeDL、ffmpegを使用して構築されたDiscordボットを再生している音楽を起動します。"

#: run.py:690
msgid "Available via Github:"
msgstr "Github で利用可能:"

#: run.py:694
msgid "For more help and support with this bot, join our discord:"
msgstr "このボットでより多くの助けとサポートが得られるように、私たちのdiscordに参加してください。"

#: run.py:696
msgid "This software is provided under the MIT License."
msgstr "このソフトウェアはMITライセンスの下で提供されています。"

#: run.py:698
msgid "See the `LICENSE` text file for complete details."
msgstr "詳細については、 `LICENSE` テキストファイルを参照してください。"

#: run.py:710
msgid ""
"Override the default / system detected language for all text in MusicBot."
msgstr "MusicBotのすべてのテキストのデフォルト/システム検出言語を上書きします。"

#: run.py:719
msgid "Use this language for all server-side log messages from MusicBot."
msgstr "MusicBotからのすべてのサーバーサイドログメッセージにこの言語を使用します。"

#: run.py:728
msgid ""
"Use this language for all messages sent to discord from MusicBot.\n"
"This does not prevent per-guild language selection."
msgstr ""
"MusicBotからDiscordに送信されたすべてのメッセージにこの言語を使用してください。\n"
"ギルド毎の言語の選択を防ぐことはできません。"

#: run.py:739
msgid "Print the MusicBot version information and exit."
msgstr "MusicBot のバージョン情報を印刷して終了します。"

#: run.py:747
msgid "Skip all optional startup checks, including the update check."
msgstr "アップデートチェックを含む、オプションの起動チェックをすべてスキップします。"

#: run.py:755
msgid "Skip only the disk space check at startup."
msgstr "起動時にディスク容量の確認だけをスキップします。"

#: run.py:763
msgid "Skip only the update check at startup."
msgstr "起動時にアップデートの確認だけをスキップします。"

#: run.py:772
msgid ""
"Disable MusicBot from trying to install dependencies when it cannot import "
"them."
msgstr "MusicBot が依存関係をインポートできない場合のインストールを無効にします。"

#: run.py:783
#, python-format
msgid ""
"Specify how many log files to keep, between 0 and %s inclusive. (Default: "
"%s)"
msgstr "保存するログ ファイルの数を指定します。0 から %s までです。(デフォルト: %s)"

#: run.py:793
#, python-format
msgid "Override the log level settings set in config. Must be one of: %s"
msgstr "設定で設定されたログレベルの設定を上書きします。以下のいずれかにする必要があります： %s"

#: run.py:804
#, python-format
msgid ""
"Override the default date format used when rotating log files. This should "
"contain values compatible with strftime().  (Default:  '%s')"
msgstr ""
"ログファイルを回転させるときに使用されるデフォルトの日付書式を上書きします。これは、strftime() "
"と互換性のある値を含む必要があります。(デフォルト: '%s')"

#: run.py:827
#, python-format
msgid "Version:  %s"
msgstr "バージョン：  %s"

#: run.py:902
msgid "Opened a new MusicBot instance. This terminal can be safely closed!"
msgstr "新しいMusicBotインスタンスを開きました。この端末は安全に閉じることができます！"

#: run.py:973
#, python-format
msgid "Loading MusicBot version:  %s"
msgstr "MusicBot のバージョンを読み込み中:  %s"

#: run.py:974
#, python-format
msgid "Log opened:  %s"
msgstr "ログを開きました:  %s"

#: run.py:975
#, python-format
msgid "Python version:  %s"
msgstr "Python version:  %s"

#: run.py:984
#, python-format
msgid "Changing working directory to:  %s"
msgstr "作業ディレクトリの変更:  %s"

#: run.py:988
msgid ""
"Cannot start the bot!  You started `run.py` in the wrong directory and we "
"could not locate `musicbot` and `.git` folders to verify a new directory "
"location."
msgstr ""
"ボットを起動できません！`run.py`を間違ったディレクトリから起動したため、`musicbot`と`が見つかりませんでした。 "
"新しいディレクトリの場所を確認するためのフォルダです。"

#: run.py:993
msgid ""
"For best results, start `run.py` from the same folder you cloned MusicBot into.\n"
"If you did not use git to clone the repository, you are strongly urged to."
msgstr ""
"MusicBotをクローンしたフォルダから、`run.py`を起動してください。\n"
"リポジトリのクローンにgit を使用していない場合は、強くお勧めします。"

#: run.py:1047
msgid ""
"Certificate error is not a verification error, not trying certifi and "
"exiting."
msgstr ""
"Certificate error is not a verification error not trying certifi and "
"exiting."

#: run.py:1049
msgid "Here is the exact error, it could be a bug."
msgstr "ここに正確なエラーがあり、バグがある可能性があります。"

#: run.py:1065
msgid ""
"To easily add a certificate to Windows trust store, \n"
"you can open the failing site in Microsoft Edge or IE...\n"
msgstr ""

#: run.py:1071
msgid ""
"Could not get Issuer Certificate from default trust store, trying certifi "
"instead."
msgstr "デフォルトのトラストストアから発行者証明書を取得できませんでした。代わりに証明書を試してみてください。"

#: run.py:1080
msgid "Syntax error (modification detected, did you edit the code?)"
msgstr "構文エラー（変更が検出されました。コードを編集しましたか？）"

#: run.py:1083
msgid "Syntax error (this is a bug, not your fault)"
msgstr "構文エラー（これはバグであり、障害ではありません）"

#: run.py:1095
msgid ""
"Cannot start MusicBot due to an error!\n"
"\n"
"Problem:\n"
"  There was an error importing MusicBot or a dependency package.\n"
"\n"
"Solution:\n"
"  You need to manually install pip packages for MusicBot\n"
"  or launch without `--no-install-deps` and MusicBot will try to install them for you."
msgstr ""

#: run.py:1128
msgid "Attempting to install MusicBot dependency packages automatically...\n"
msgstr "MusicBot依存パッケージを自動的にインストールしようとしています...\n"

#: run.py:1137
#, python-format
msgid ""
"MusicBot dependencies may not be installed!\n"
"\n"
"Problem:\n"
"  The pip install process ended with a possible error.\n"
"  Some or all of the the dependencies may be missing.\n"
"\n"
"Solution:\n"
"  You must manually install dependency packages.\n"
"  Open a CMD prompt / terminal to the MusicBot directory.\n"
"  You can try using the update scripts install packages.\n"
"  Or try this manual command:\n"
"    %(py_bin)s -m pip install -U -r ./requirements.txt\n"
"\n"
"You can also ask for help in MusicBot's support discord:\n"
"  https://discord.gg/bots"
msgstr ""

#: run.py:1158
msgid "OK, lets hope installing dependencies worked!"
msgstr "OK、依存関係のインストールがうまくいったことを願っています！"

#: run.py:1170
msgid ""
"MusicBot got an ImportError after trying to install packages. MusicBot must "
"exit..."
msgstr ""
"MusicBot がパッケージをインストールしようとしてImportError を受け取りました。MusicBot は終了する必要があります..."

#: run.py:1172
msgid "The exception which caused the above error: "
msgstr "上記のエラーを引き起こした例外: "

#: run.py:1191
msgid "MusicBot is doing a soft restart..."
msgstr "MusicBot がソフトな再起動を行っています..."

#: run.py:1195
msgid "MusicBot is doing a full process restart..."
msgstr "MusicBot が完全な再起動処理を行っています..."

#: run.py:1201
msgid "Error starting bot"
msgstr "ボット起動時のエラー"

#: run.py:1206
msgid "Closing event loop."
msgstr "イベントループを閉じています。"

#: run.py:1211
#, python-format
msgid "Restarting in %s seconds..."
msgstr "%s 秒後に再起動中..."

#: run.py:1215
msgid "All done."
msgstr "すべて完了です。"

#: run.py:1244
msgid "OK, we're closing!"
msgstr "OK、閉店中です！"

#: musicbot/bot.py:2147
msgid "MusicBot is now doing start up steps..."
msgstr ""

#: musicbot/bot.py:2154
msgid "Start up failed at login."
msgstr ""

#: musicbot/bot.py:3410
#, python-format
msgid "No playlist file exists with the name: `%(playlist)s`"
msgstr ""

#: musicbot/bot.py:5083
msgid ""
"There is nothing currently playing. Play something with a play command."
msgstr ""

#: musicbot/bot.py:5097
#, python-format
msgid ""
"Missing permissions to delete queue file for %(guild)s(%(id)s) at: %(path)s"
msgstr ""

#: musicbot/bot.py:5102
#, python-format
msgid "OS level error while trying to delete queue file: %(path)s"
msgstr ""

#: musicbot/config.py:1064
msgid "Generating new config options files..."
msgstr ""

#: musicbot/config.py:1074
#, python-format
msgid ""
"Error creating default config options file.\n"
"\n"
"Problem:\n"
"  MusicBot attempted to generate the config files but failed due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure MusicBot can read and write to your config files.\n"
msgstr ""

#: musicbot/config.py:1339
#, python-format
msgid ""
"Could not locate config options or example options files.\n"
"MusicBot will generate the config files at the location:\n"
"  %(cfg_file)s"
msgstr ""

#: musicbot/filecache.py:332
msgid "Cachemap defer flag is set, not yet saving to disk..."
msgstr ""

#: musicbot/permissions.py:136
#, python-format
msgid ""
"Could not locate config permissions or example permissions files.\n"
"MusicBot will generate the config files at the location:\n"
"  %(perms_file)s"
msgstr ""

#: musicbot/permissions.py:163
msgid "Generating new config permissions files..."
msgstr ""

#: musicbot/permissions.py:172
#, python-format
msgid ""
"Error creating default config permissions file.\n"
"\n"
"Problem:\n"
"  MusicBot attempted to generate the config files but failed due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure MusicBot can read and write to your config files.\n"
msgstr ""

#: run.py:523
#, python-format
msgid ""
"MusicBot could not write files in the following directory:\n"
"%(dir)s"
msgstr ""

#: run.py:527
msgid "Please make sure MusicBot can read and write in the above directory."
msgstr ""

#: run.py:534
msgid "Failed to clean up write-test path."
msgstr ""

#: run.py:817
msgid ""
"Supply a directory where MusicBot can store all mutable files.\n"
"Essentially treats the install directory as read-only.\n"
"MusicBot must have permission to create this directory.\n"
msgstr ""

#, python-format
#~ msgid "Generated a new %(example_file)s and copied it to %(option_file)s"
#~ msgstr "新しい %(example_file)s を生成し、 %(option_file)sにコピーしました。"

#~ msgid "Current working directory does not seem to be writable"
#~ msgstr "Current working directory does not be writable"

#~ msgid "Please move the bot to a folder that is writable"
#~ msgstr "Botを書き込み可能なフォルダに移動してください"
